### ISSUE TITLE
Selecting an already added stack tag removes it from the list

### ISSUE THREAD

**Issue by rpowis** [airpair/airpair-com-v1-issue-tracker#102]
Given I have the 'Customize AirPair to your Stack' modal open
And I have already searched for and added a technology/language to the list on the right
When I search for the same technology/language and click it
Then it gets removed from the list on the right

**Comment by jkresner** [comment]
Sorry, I've read this a few times over the last week, and I haven't been able to follow along. I think what you are describing is expected behavior...

**Comment by rpowis** [comment]
Possibly, if that's the case then I guess I'm suggesting a UX improvement :smile:  
Here's a gif of what I mean..

![customize-airpair-to-your-stack](https://cloud.githubusercontent.com/assets/1752124/6083030/aeb48bb4-ae1d-11e4-88ef-f53449346501.gif)

As it's possible to remove a tag using the `x` icon, also being able to remove it by selecting it again from the dropdown seems like an unexpected behaviour.

Hope that makes more sense.

**Comment by jkresner** [comment]
What should it do? Just not show the tag in the results of the search?
