### ISSUE TITLE
Send verification email brings me to login page

### ISSUE THREAD

**Issue by nouellette** [airpair/airpair-com-v1-issue-tracker#106]
I went here and typed in my email address
https://www.airpair.com/me

I got the email as expected...this time (https://github.com/airpair/airpair-com-v1-issue-tracker/issues/105) with a token and when clicking on a link i just went to a page where it asked me to login with google or user my user name and password, thats fine but I don't have a password because of the other issue.

Since I didn't get a verification token when signing up I couldn't create a password using this link:
https://www.airpair.com/me/password?token=

Seems odd that there are two endpoints for password (shown above) and verify (shown below)
https://www.airpair.com/me?verify=

**Comment by jkresner** [comment]
Thanks, I've seen the token not generate now once or twice in the logs... I'll look out for this.

**Comment by nouellette** [comment]
If your writing your own encrypt solution make sure + symbols don't get generated. If you strip them out you won't see this issue.

- Neil
