### ISSUE TITLE
Broken links are broken

### ISSUE THREAD

**Issue by mjball** [airpair/airpair-com-v1-issue-tracker#108]
From the "Book an expert" page (example: https://www.airpair.com/book/zopatista) the following nav links are broken:

- "New request" https://www.airpair.com/find-an-expert
- "Expert profile" https://www.airpair.com/be-an-expert
- "Settings" https://www.airpair.com/settings

![image](https://cloud.githubusercontent.com/assets/378111/5990731/437e85c2-a98e-11e4-815a-800c6ed14903.png)

**Comment by jkresner** [comment]
Thanks, these experts pages are the last pages of the old site to be
retired in the next two weeks. Cheers.
ᐧ

On Sat, Jan 31, 2015 at 6:15 PM, Matt Ball <notifications@github.com> wrote:

> From the "Book an expert" page (example:
> https://www.airpair.com/book/zopatista) the following nav links are
> broken:
>
>    - "New request" https://www.airpair.com/find-an-expert
>    - "Expert profile" https://www.airpair.com/be-an-expert
>    - "Settings" https://www.airpair.com/settings
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/378111/5990731/437e85c2-a98e-11e4-815a-800c6ed14903.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/airpair/airpair-com-v1-issue-tracker/issues/108>.
>



-- 
Jonathon Kresner
about.me <http://about.me/jonathonkresner> | hackerpreneurialism
<http://hackerpreneurialism.com> | @hackerpreneur
<http://twitter.com/hackerpreneur>

**Comment by jkresner** [comment]
These links are back up thank you.
