### ISSUE TITLE
Spelling mistake for Contribute on new Blogs View

### ISSUE THREAD

**Issue by mappmechanic** [airpair/airpair-com-v1-issue-tracker#109]
May be it is just an oversight but you should correct the spelling for "Contribute" it is written "Contibute"
![screen shot 2015-02-02 at 12 47 01 am](https://cloud.githubusercontent.com/assets/4088925/5993432/53be8886-aa76-11e4-8a2d-2f659b02b342.png)

**Comment by jkresner** [comment]
Fixed :8ball:
