### ISSUE TITLE
Textarea in Expert Application page does not autogrow 

### ISSUE THREAD

**Issue by ajoslin** [airpair/airpair-com-v1-issue-tracker#111]
If I type more than two lines, I have to manually scroll the textarea at https://www.airpair.com/expert-applications.

**Comment by jkresner** [comment]
Thanks this was a great suggestion, I've added this featured to the "Why do you want to AirPair" text area on the expert application page and will put it in other places that make sense.

![Uploading Screen Shot 2015-03-11 at 12.50.42 PM.png . . .]()
