### ISSUE TITLE
Aldo's post on JavaScript array reduce needs fixes

### ISSUE THREAD

**Issue by dandv** [airpair/airpair-com-v1-issue-tracker#112]
https://www.airpair.com/javascript/javascript-array-reduce is how I learned about AirPair. It's in the first page of Google search results for "JavaScript map reduce", even though the post has been criticized in the comments section for the past year.

* misspelled variables
* copy/paste incorrect code
* smart quotes instead of `"`

**Comment by jkresner** [comment]
Well isn't this great timing with the announcement next tuesday of our git powered reader forks and suggested edits.

Now we just have to find out where @aldonline is theres days, so he can create the repo from our UI 

![screen shot 2015-02-06 at 8 14 44 am](https://cloud.githubusercontent.com/assets/979542/6082707/3fb01700-add8-11e4-9ab1-ff506bb17f38.png)


![screen shot 2015-02-05 at 12 10 46 pm](https://cloud.githubusercontent.com/assets/979542/6082674/0a871de4-add8-11e4-9d13-359de9b30165.png)

**Comment by dandv** [comment]
:+1:

**Comment by aldonline** [comment]
Hey @jkresner  - I tried publishing but I get a "Must be editor to update a published post" error.

**Comment by aldonline** [comment]
Maybe it's because the article is below 500 words?
Either way, here's the updated markdown: https://gist.github.com/aldonline/b2b723efca26170b7cc7

**Comment by jkresner** [comment]
We just need you to "Submit for review" so that we can fork and create a PR for you to accept. Then our edits will propagate the latest from the github repo.

**Comment by jkresner** [comment]
@aldonline https://www.airpair.com/posts/submit/545c1b351a58ce0b00c0f0af and then you can edit

**Comment by aldonline** [comment]
Ok I was now able to do it. ( You removed the 500 words limit? )
I tried both the online editor and directly on Github. Works great ;)
Here's the repo: https://github.com/airpair/understand-javascript-array-reduce-in-1-minute

When I tried to publish I got this message:
"The live version of your post is behind HEAD on github. If it's ready to be updated, request an editor to sync your changes."

**Comment by aldonline** [comment]
BTW - For some reason the code blocks were not indented when the repo was created so I had to fix that. It is possible the original article did not have this indentation. I am just bringing this up so you keep an eye on this. It may be a more general issue.

**Comment by jkresner** [comment]
We originally didn't support github flavored code syntax ... Not sure it
has anything to do with it.

Should be ok if you're happy with how the post looks now?

Jonathon
ᐧ

On Wed, Feb 25, 2015 at 6:01 PM, Aldo Bucchi <notifications@github.com>
wrote:

> BTW - For some reason the code blocks were not indented when the repo was
> created so I had to fix that. It is possible the original article did not
> have this indentation. I am just bringing this up so you keep an eye on
> this. It may be a more general issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/airpair/airpair-com-v1-issue-tracker/issues/112#issuecomment-76108796>
> .
>



-- 
Jonathon Kresner
about.me <http://about.me/jonathonkresner> | hackerpreneurialism
<http://hackerpreneurialism.com> | @hackerpreneur
<http://twitter.com/hackerpreneur>
