### ISSUE TITLE
Github integration is not working for me

### ISSUE THREAD

**Issue by gsans** [airpair/airpair-com-v1-issue-tracker#114]
Im trying to publish a post but You won't let me until I get this Github connection sorted.

I have tried from 'posts' an from my account pages. On Github under applications it shows so I dont really understand whats going on.

Tried also from firefox and chrome with same results:

Error
failed to fetch user profile

Console
"NetworkError: 400 Bad Request - https://www.airpair.com/auth/github/callback?code=44796f259441270a32af"

**Comment by jkresner** [comment]
@gsans 

Sorry, I deployed at 3:30am and had the github application clientSecret incorrectly configured. Working now!
