### ISSUE TITLE
Typo in "Site Updates" post.

### ISSUE THREAD

**Issue by dcessna** [airpair/airpair-com-v1-issue-tracker#115]
Should say "We know things haven't felt cohesive" instead of "We known things haven't felt cohesive".

![screen shot 2015-02-05 at 5 50 43 pm](https://cloud.githubusercontent.com/assets/223309/6071818/dbb6a034-ad5f-11e4-8dc5-9d427e128ef3.png)

**Comment by jkresner** [comment]
Thank you! $10 has been credited to you account :)
