### ISSUE TITLE
Why duplicating content?

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#116]
Is there a reason why this post is here twice - Gerard's.

![screen shot 2015-02-05 at 18 07 34](https://cloud.githubusercontent.com/assets/857253/6072065/870053fc-ad62-11e4-8fa3-244d0a0040c2.png)

Or why Adam has 2, with different titles of the same thing? 

![screen shot 2015-02-05 at 18 10 42](https://cloud.githubusercontent.com/assets/857253/6072066/8a43ad5c-ad62-11e4-96bd-290b20895bc5.png)

Is it not easy for users to edit old posts?

**Comment by jkresner** [comment]
Yes, there were issues causing inconsistent states against the api. Hopefully this won't happen from now.
