### ISSUE TITLE
Timezone is wrong, using summer time in the winter

### ISSUE THREAD

**Issue by rwillmer** [airpair/airpair-com-v1-issue-tracker#118]
I've entered my city as Edinburgh, UK. My timezone is being shown as British Summer Time.

As I look out the window at the snow threatening to start on a cold February morning, I can assure you that it is not summer :)

**Comment by jkresner** [comment]
That's funny.  The data comes from Moment Timezone. Guess they made a bo bo, or a joke. Personally I prefer it to Standard Time!

**Comment by mjpieters** [comment]
Moreover, I cannot *clear* the location field again, so now my profile is stuck with timezone info that is off by an hour. Is the timezone used to communicate availability with clients? That would be rather inconvenient, having to explain that all the times are off by one hour.

**Comment by jkresner** [comment]
Can you both try it again? I believe it had to do with a hardcoded time (1970) for the date lookup.

https://www.airpair.com/me

**Comment by mjpieters** [comment]
It's a little hard to confirm or deny the issue now that it is, in fact, British Summer Time. :stuck_out_tongue:

**Comment by jkresner** [comment]
Ha ha ha, could be worse!!!!

**Comment by asdra50** [comment]
FUCK YOURSELF @mjpieters @thefourtheye @ztane @Ffisegydd @vaultah

**Comment by asdra50** [comment]
FUCK YOURSELF @mjpieters @thefourtheye @ztane @Ffisegydd @vaultah

**Comment by asdra50** [comment]
FUCK YOURSELF @mjpieters @thefourtheye @ztane @Ffisegydd @vaultah

**Comment by asdra50** [comment]
FUCK YOURSELF @mjpieters @thefourtheye @ztane @Ffisegydd @vaultah

**Comment by asdra50** [comment]
FUCK YOURSELF @mjpieters @thefourtheye @ztane @Ffisegydd @vaultah

**Comment by asdra50** [comment]
FUCK YOURSELF @mjpieters @thefourtheye @ztane @Ffisegydd @vaultah

**Comment by asdra50** [comment]
FUCK YOURSELF @mjpieters @thefourtheye @ztane @Ffisegydd @vaultah

**Comment by asdra50** [comment]
FUCK YOURSELF @mjpieters @thefourtheye @ztane @Ffisegydd @vaultah

**Comment by asdra50** [comment]
FUCK YOURSELF @mjpieters @thefourtheye @ztane @Ffisegydd @vaultah

**Comment by asdra50** [comment]
FUCK YOURSELF @mjpieters @thefourtheye @ztane @Ffisegydd @vaultah
