### ISSUE TITLE
Left Navigation

### ISSUE THREAD

**Issue by gholzmacher** [airpair/airpair-com-v1-issue-tracker#119]
Regarding the left hand nav, whenever I hover over to select the alerts the nav pops out and there doesnt seem to be any reference to what the alerts are in the full nav. Also the three bar button doesn't lock the nav in place.

I am unsure what the alerts are in reference to, but I have three of them and am unable to click the icon to find out so I assume this is unintentional. 

I am using chrome. 
![image](https://cloud.githubusercontent.com/assets/3395540/6082229/a575a5f4-aded-11e4-88c5-8a3b4788daa4.png)

**Comment by jkresner** [comment]
We're getting close to a redesign of this menu system. Either a week or two from now you'll see it updated quite a bit.

**Comment by gholzmacher** [comment]
Thanks Jonathon! I really like the business model, you guys are going places! Need help?

**Comment by jkresner** [comment]
Always need help... what are you referring to:?

**Comment by gholzmacher** [comment]
Are you guys hiring or do you source work through contractors on AirPair?

**Comment by jkresner** [comment]
Hiring

**Comment by dcbartlett** [comment]
+1 to the menu, and +1 to hiring, gonna go see where to apply
