### ISSUE TITLE
Send Email Verification won't use the email I entered.

### ISSUE THREAD

**Issue by nedbat** [airpair/airpair-com-v1-issue-tracker#121]
I used my work browser (Chrome) to visit the page https://www.airpair.com/expert-applications .  It had my email filled in as "ned@edx.org".  I wanted to use my personal email, so I entered it: ned@nedbatchelder.com.  I clicked Send Email Verification, and it sent a verification to ned@edx.org.

**Comment by jkresner** [comment]
This use case should no longer exist. Are you able to set and verify the email you want ?
