### ISSUE TITLE
Code snippets no longer formatted

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#122]
Code snippets no longer formatted in existing articles e.g https://www.airpair.com/swift/complete-guide-to-swift

![screen shot 2015-02-07 at 10 00 36](https://cloud.githubusercontent.com/assets/857253/6092717/5df1d356-aeb0-11e4-9831-8b1cdea53c97.png)

**Comment by jkresner** [comment]
Fixed!
