### ISSUE TITLE
TOC positioning on loading post

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#123]
TOC appears underneath & over main text when loading

![screen shot 2015-02-07 at 10 03 45](https://cloud.githubusercontent.com/assets/857253/6092722/c9750b5c-aeb0-11e4-9bc5-c0e24db9572a.png)
![screen shot 2015-02-07 at 10 03 56](https://cloud.githubusercontent.com/assets/857253/6092721/c9717564-aeb0-11e4-9d17-70ba642e4e8f.png)

**Comment by jkresner** [comment]
Fixed :)
