### ISSUE TITLE
Github app should not ask for permission to write profile data and private repos

### ISSUE THREAD

**Issue by pentium10** [airpair/airpair-com-v1-issue-tracker#125]
As you can see here:
http://screencast.com/t/peYRuhQwjM4

requesting write access to profile data and **private repos** is something DANGEROUS.

**Comment by sbahra** [comment]
Ping. I cannot link to my github until this is resolved.

**Comment by jkresner** [comment]
Thanks guys. The scope is hardcoded as it's mostly facilitating out new
github authoring tools. We'll put some mechanics in place for less
permission just for expert profiles as we release that feature.
ᐧ

On Mon, Feb 9, 2015 at 1:26 PM, Samy Al Bahra <notifications@github.com>
wrote:

> Ping. I cannot link to my github until this is resolved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/airpair/airpair-com-v1-issue-tracker/issues/125#issuecomment-73593490>
> .
>



-- 
Jonathon Kresner
about.me <http://about.me/jonathonkresner> | hackerpreneurialism
<http://hackerpreneurialism.com> | @hackerpreneur
<http://twitter.com/hackerpreneur>

**Comment by destan** [comment]
@sbahra :+1: 

@jkresner  If you opensource it we could fix it ;)

**Comment by mjpieters** [comment]
Same applies to BitBucket; neither account can be linked with the permissions as requested; I'd be in breach of NDAs if I did.

**Comment by jkresner** [comment]
We only ask for public repo access now. As for open sourcing some of AirPair - add your name to this readme if you are really serious @destan https://github.com/airpair/experts.airpair.com
