### ISSUE TITLE
Verification email didn't show up

### ISSUE THREAD

**Issue by destan** [airpair/airpair-com-v1-issue-tracker#127]
Verification email didn't show up until I manually resend it via this page: https://www.airpair.com/me

Before that I have tried resending verification email button on https://www.airpair.com/expert-applications page but it didn't worked

**Comment by tmornini** [comment]
Me too. :-)

**Comment by jkresner** [comment]
@destan @tmornini this page has been replaced with a newer version. Are you able to fill out the form and verify the email address you want?
