### ISSUE TITLE
Clicking stackoverlow link for a pairing request fails

### ISSUE THREAD

**Issue by mjmj** [airpair/airpair-com-v1-issue-tracker#128]
Was at a review page looking at potential matches to book and noticed the stackoverflow link was broken when clicking on it.

For example I was here:
1. https://www.airpair.com/review/54dbcc3ed821240a00141482
2. Click on stackoverflow button for 'Mark Butler' 
Result: https://www.airpair.com/802012/mark-butler
Returns: Cannot GET /802012/mark-butler

His actual S.O. profile page: http://stackoverflow.com/users/802012/mark-butler

**Comment by jkresner** [comment]
Thanks, fixed in tonight's deploy. I have credited your account $10. :)

**Comment by mjmj** [comment]
Awesome thanks!
