### ISSUE TITLE
Cannot reply to this request, as it is not active

### ISSUE THREAD

**Issue by MaTriXy** [airpair/airpair-com-v1-issue-tracker#133]
Accessing to AirPair match and trying to post reply to customer yields the message:
"Cannot reply to this request, as it is not active"

![image](https://cloud.githubusercontent.com/assets/3080139/6163157/0042fd26-b297-11e4-9052-73d13cf2cdae.png)

**Comment by jkresner** [comment]
Can you describe what you saw at each step?

**Comment by MaTriXy** [comment]
1. Clicked the link
2. opened the page
3. Clicked on I'm Available
4. Filled Message and Availability time
5. Clicked send reply 
6. Got the Message above.

**Comment by mjpieters** [comment]
I experienced this just now too; the request was from last week and I was sure I had responded to it already, but I cannot give a new response. Perhaps that's a crucial step in reproducing this, perhaps this only applies to items you already responded to and the bug is that it is not showing the already recorded response?

**Comment by mikegrassotti** [comment]
Just had the same issue, has happened to me a few times over past couple weeks. Here's what happened:

- Followed this link from the airpair twitter feed: https://twitter.com/airpair/status/567389656581689345

- Request looked like it was still active. Filled out the form and hit submit
- Got error "Cannot reply to this request, as it is not active"

![airpair___ruby-on-rails__heroku_and_postgresql_request](https://cloud.githubusercontent.com/assets/19201/6239096/89c5185a-b6ce-11e4-92e5-a8197c98ee28.png)

**Comment by MaTriXy** [comment]
The issue arise when the client chose someone and the request wasn't updated to closed.

**Comment by jkresner** [comment]
Thanks guys, will be attacking this one as soon as I can. Just finishing
off the final bits of our new posts system and it will be all expert
features from here on.
ᐧ

On Tue, Feb 17, 2015 at 10:10 PM, Yossi Elkrief <notifications@github.com>
wrote:

> The issue arise when the client chose someone and the request wasn't
> updated to closed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/airpair/airpair-com-v1-issue-tracker/issues/133#issuecomment-74818176>
> .
>



-- 
Jonathon Kresner
about.me <http://about.me/jonathonkresner> | hackerpreneurialism
<http://hackerpreneurialism.com> | @hackerpreneur
<http://twitter.com/hackerpreneur>

**Comment by kjsowards** [comment]
Just occurred with an airpair that was 'selected' for me through an email.

• Click email link
• Browser openen, filled out form
• Submission come back with that 'not active' error.

![screenshot 2015-02-21 21 44 59](https://cloud.githubusercontent.com/assets/634548/6317350/18d9512c-ba13-11e4-91ff-b8afdc3834ec.png)

**Comment by jlettvin** [comment]
It happened to me too.
Task was selected for me.
https://www.airpair.com/review/54ec8b616e9ac20c004e1fa4

**Comment by jkresner** [comment]
Sorry will try to get to this tomorrow. Thanks for your patience.

**Comment by jkresner** [comment]
Hey @MaTriXy  & @mjpieters, @kjsowards & @jlettvin , I want to apologize for how long this has taken. I got very side tracked these last weeks with all the authoring stuff we've been working on and we haven't had enough dev resource to push both core expert stuff and the comp. The good news is that the comp stuff is mostly done and for the next 4-6 weeks I will be primarily focused on expert features, and part of the reason I didn't get to this part of the code is we're about to step up the experience around replying to requests by 10x. 

Finally I'm planning to build a lot of it open source. You would be most welcome to code review and fix bugs in your reach as I go:

https://github.com/airpair/experts.airpair.com

![screen shot 2015-03-12 at 1 19 06 pm](https://cloud.githubusercontent.com/assets/979542/6627372/e4545daa-c8ba-11e4-9925-9885ace6b640.png)
