### ISSUE TITLE
The text here isn't worded right, see bold

### ISSUE THREAD

**Issue by c316** [airpair/airpair-com-v1-issue-tracker#134]
Recenly added in the last 8 weeks

Improved our post authoring tools with a greatly improved edits and a new github backed collaboration authors flow.
**We've be finalized the get help form.**

Read more at https://www.airpair.com/100K-writing-competition/sponsors-faq#s5GYdwZeMs1sUmPK.99

**Comment by jkresner** [comment]
Would you like to try out our new forking feature roll out 2 minutes ago :) ? 

![screen shot 2015-02-12 at 10 32 09 pm](https://cloud.githubusercontent.com/assets/979542/6183223/09b82a64-b307-11e4-96ce-8cc09c250f16.png)
