### ISSUE TITLE
Wrong link on View Button on publish screen

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#136]
![screen shot 2015-02-12 at 20 25 38](https://cloud.githubusercontent.com/assets/857253/6181218/5eeee700-b2f5-11e4-9a4a-fdc6dfa2708e.png)

**Comment by jkresner** [comment]
Can you take a screenshot of the whole page. Are you looking at the publish page?

**Comment by EllDudley** [comment]
Yep, on publish screen 
![screen shot 2015-02-13 at 09 17 08](https://cloud.githubusercontent.com/assets/857253/6189551/2421f786-b361-11e4-8d13-2515941f4760.png)
