### ISSUE TITLE
Unclear messaging to update a published post

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#137]
![screen shot 2015-02-12 at 20 10 36](https://cloud.githubusercontent.com/assets/857253/6181241/a75203f6-b2f5-11e4-8e66-6547c1606a16.png)

It's not clear to me that the HEAD on github has MY changes... or these are other people's changes? Shouldn't I know this BEFORE I made edits in case I need to pull the latest first? Or is this the latest? 

What if the editor hasn't pulled the latest version? And how do I even get notified that I need to pull someone's latest version. I know this is only once published, but I imagine it will happen...

**Comment by jkresner** [comment]
You are the one making all edits or accepting any suggestions on github, so you would know what those changes are.

This message isn't looking at the editor it is looking at the file on github.
