### ISSUE TITLE
Broken link for /be-an-expert

### ISSUE THREAD

**Issue by mansona** [airpair/airpair-com-v1-issue-tracker#138]
Steps to recreate: 
* go to a job e.g. https://www.airpair.com/review/52e02419d0c7b20200000017 (very old i know)
* click the link "Apply to be an airpair expert" 

Expected result: 
* ... the ability to apply

Actual result: 
* Cannot GET /be-an-expert
* https://cloudup.com/c7Ccdi1OLXr

**Comment by mansona** [comment]
I assume this is related to https://github.com/airpair/airpair-com-v1-issue-tracker/issues/108 but i think the "Apply to be an airpair expert" link is important enough for re-marketing so i created this separate ticket :+1:

**Comment by jkresner** [comment]
Will be getting back to the experts stuff from next week. Thanks for your patience.

**Comment by jkresner** [comment]
Thanks this is fixed now. If interested check out this project too:

https://github.com/airpair/experts.airpair.com
