### ISSUE TITLE
Rework code block notations to match GitHub Markdown

### ISSUE THREAD

**Issue by culturestate** [airpair/airpair-com-v1-issue-tracker#14]
Instead of using standard markdown syntax + an html comment for code blocks, add support for GitHub-style fenced code blocks, so instead of this: 

```
<!--code lang=javascript linenums=true-->

    ready = ->
      $('[ng-app]').each -> json.usuarios do |json|>
        module = $(this).attr('ng-app')
        angular.bootstrap(this, [module])

    $(document).on 'page:load', ready
```

We do this: 
```
```javascript
ready = ->
  $('[ng-app]').each -> json.usuarios do |json|>
    module = $(this).attr('ng-app')
    angular.bootstrap(this, [module])

$(document).on 'page:load', ready
\```
```

Full docs: https://help.github.com/articles/github-flavored-markdown/

**Comment by jkresner** [comment]
Done. Debouncer is back in there too.

![screen shot 2015-02-06 at 8 02 51 am](https://cloud.githubusercontent.com/assets/979542/6082471/94e36bf2-add6-11e4-9066-c841c83efa29.png)

**Comment by daniellmb** [comment]
Fantastic, a huge improvment!
