### ISSUE TITLE
Cannot GET /be-an-expert

### ISSUE THREAD

**Issue by zackster** [airpair/airpair-com-v1-issue-tracker#140]
![https___www_airpair_com_be-an-expert](https://cloud.githubusercontent.com/assets/81474/6233771/5aafde9a-b6a3-11e4-85cb-1c46bcbaceab.png)

**Comment by prtkgpt** [comment]
Hey @zackster thanks for your message. We will be opening up the expert profiles later in Feb. Please check out https://www.airpair.com/expert-applications
