### ISSUE TITLE
Content Cut at Bottom on Community Review View

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#142]
Missing last paragraph of text at bottom

![screen shot 2015-02-17 at 18 55 05](https://cloud.githubusercontent.com/assets/857253/6240624/ae4c5b36-b6d6-11e4-8f87-de1ef6085b3e.png)

On the screen:

![screen shot 2015-02-17 at 18 55 13](https://cloud.githubusercontent.com/assets/857253/6240625/ae4dae0a-b6d6-11e4-89cf-4b7d01cc4ce1.png)

**Comment by jkresner** [comment]
Fixed :)
