### ISSUE TITLE
Your GitHub post is broken? 

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#143]
![screen shot 2015-02-18 at 08 21 02](https://cloud.githubusercontent.com/assets/857253/6248718/16ddaa1c-b748-11e4-8e12-d4ab4cef7d1d.png)

When following the link in the Sponsor FAQ:

![screen shot 2015-02-18 at 08 21 11](https://cloud.githubusercontent.com/assets/857253/6248725/2354f67e-b748-11e4-9b56-79d6626e4afd.png)

**Comment by jkresner** [comment]
Think it's fixed.
