### ISSUE TITLE
Navigation Error

### ISSUE THREAD

**Issue by sri-harsha-g** [airpair/airpair-com-v1-issue-tracker#145]
Navigation Error
PAGE Navigation from : https://www.airpair.com/angularjs/posts/jquery-angularjs-comparison-migration-walkthrough -> Home Page

Browsing back to PAGE :https://www.airpair.com/angularjs/posts/jquery-angularjs-comparison-migration-walkthrough also failing and gives error

![browsing error](https://cloud.githubusercontent.com/assets/5960253/6264844/9bee5796-b84d-11e4-8c11-d4dc0799f26f.png)

**Comment by dcbartlett** [comment]
+1

**Comment by jkresner** [comment]
About page no longer exists :)
