### ISSUE TITLE
Page missing: Apply to be an expert

### ISSUE THREAD

**Issue by michaelreynolds** [airpair/airpair-com-v1-issue-tracker#148]
from this link airpa.ir/1CQmgiz I get a screen that says "apply to be an expert" button takes me to this 

page: https://www.airpair.com/be-an-expert

which returns: "Cannot GET /be-an-expert"

**Comment by michaelreynolds** [comment]
http://i.imgur.com/vNhKqvh.png

**Comment by rchrd2** [comment]
:+1:

**Comment by jkresner** [comment]
Thanks @michaelreynolds / @rchrd2 attacking this on the weekend. 

In the meantime, let me know if either want to write a blog post for our writing competition!

Jonathon
