### ISSUE TITLE
Instruction text missing from content editor

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#149]
Instruction text missing from content editor. 

![screen shot 2015-02-19 at 20 42 57](https://cloud.githubusercontent.com/assets/857253/6309211/8785b2ea-b910-11e4-8c18-04b8cbd770f8.png)

**Comment by jkresner** [comment]
What stage is the post in? Thought I deployed a fix this morning :/

**Comment by EllDudley** [comment]
Looks good now, it was this morning when I was writing the author post.
