### ISSUE TITLE
Notify authors when there's a comment on their post Disqus

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#151]
Do we do this with Disqus or only team@airpair.com gets notifications? Would be cool to update each post to include the author field:

"Author: Update this when you want a non-moderator on your Disqus forum to be considered the author for the discussion. This allows them to moderate comments on that discussion both via Disqus notification emails and inline in the commenting embed."

**Comment by jkresner** [comment]
Not following your thread... But disqus has been disabled for all new posts as the review system replaces it.
