### ISSUE TITLE
Issue while scroll down.

### ISSUE THREAD

**Issue by vamsi020** [airpair/airpair-com-v1-issue-tracker#153]
An Issue occurs while scroll down to the comment section. table of contents on right side overlaps the comment section.  

![issue1](https://cloud.githubusercontent.com/assets/5392034/6313202/235be270-b9c5-11e4-935f-443b293593fc.png)

**Comment by jkresner** [comment]
![screen shot 2015-02-23 at 10 55 34 am](https://cloud.githubusercontent.com/assets/979542/6334598/8665a2d0-bb4a-11e4-96df-8046cf7eaf1e.png)


Fix thanks
