### ISSUE TITLE
Fix Non-SSL elements on archive/posts pages

### ISSUE THREAD

**Issue by etelej** [airpair/airpair-com-v1-issue-tracker#155]
### Issue:
Visitors receiving https *warning* and broken padlock on archive sites (**/posts**, **/posts/tag** etc), that while the site has valid SSL cert, it requests unsecured (http) resources.

### Cause:
Thumbnails for posts are requested using *http://* absolute URLs.

### Resolution:
I noticed that almost all the images used in posts allow for *https* access on their various domains, e.g imgur, amazonaws, youtu.be, github.io... The only one that I noticed would have an issue accessing was a thumbnail requested from f.cl.ly; apart from that, using protocol relative URLs suffice eg 
```
<img src="//domain.com/img/logo.png">
```
 as seen [here](http://www.paulirish.com/2010/the-protocol-relative-url/). Though, as recommended, using **https://** absolute URLs would simply be better.
- Maybe the few images without *https* access alternative, can be automatically checked and either re-uploaded, or __*an easier option*__ would be in that instance using a default thumbnail.

**Comment by jkresner** [comment]
Thanks for pointing this out. Duplicate issue logged here. It may take some time before we've gone through and fixed all the older posts.

https://github.com/airpair/airpair-com-v1-issue-tracker/issues/58
