### ISSUE TITLE
Review the timezones source

### ISSUE THREAD

**Issue by lu1s** [airpair/airpair-com-v1-issue-tracker#157]
The timezone does not correspond to the city. For example, I selected Hermosillo, Mexico, and it shows the PST when it should be MT.
Could be happening with other cities.
![screen shot 2015-02-23 at 8 46 17 pm](https://cloud.githubusercontent.com/assets/615093/6342348/57dac03c-bb9d-11e4-9065-0b878299f8ed.png)

**Comment by jkresner** [comment]
Will look into this next month. The timezone comes from google's timezone service.
