### ISSUE TITLE
Change link of https://www.airpair.com/posts/authoring-faq

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#158]
It doesn't go anywhere - can we send it to Author FAQ - https://www.airpair.com/posts/preview/54e33a70ec7cf70a00829703
![screen shot 2015-02-25 at 08 33 27](https://cloud.githubusercontent.com/assets/857253/6372332/0778677a-bcc9-11e4-95f8-a6f7863e75fe.png)

**Comment by jkresner** [comment]
When we publish we'll give it this url

**Comment by jkresner** [comment]
This was fixed recently :)
