### ISSUE TITLE
Editing a Post - code blocks appear on top of the Navigation Breadcrumb - UI Bug

### ISSUE THREAD

**Issue by mappmechanic** [airpair/airpair-com-v1-issue-tracker#159]
While I was editing a post, I found out that the code element has greater z-index than some of the other elements like the navigation breadcrumb which creates some problem while I am authoring a post.

I am attaching the screenshot for anyone to understand this issue better.

![screen shot 2015-02-25 at 8 39 20 pm](https://cloud.githubusercontent.com/assets/4088925/6373107/bf6e5a32-bd2e-11e4-9b3b-530a2bc292c3.png)

**Comment by jkresner** [comment]
@mappmechanic can you repoduce on the newer version and let me know what browser you're using?
