### ISSUE TITLE
Spelling change on edit post flow

### ISSUE THREAD

**Issue by dwanderton** [airpair/airpair-com-v1-issue-tracker#162]
On the publish page for posts once edited text says 'up to do' - should be 'up-to-date'

![screen_shot_2015-02-22_at_12 43 05](https://cloud.githubusercontent.com/assets/3466284/6378965/97183eb8-bce3-11e4-84fe-34b80ed69fa6.png)

**Comment by jkresner** [comment]
Thanks, I don't think this sentence exists anymore :)
