### ISSUE TITLE
Add a link to access post from contributors page

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#163]
Eric let me know he made an update but I can't access his post from this link:

https://www.airpair.com/posts/contributors/54e8eed2aed27c0c00cf26f1

![screen shot 2015-02-26 at 08 06 38](https://cloud.githubusercontent.com/assets/857253/6393304/8742c4a8-bd8e-11e4-856d-19881192c636.png)

**Comment by jkresner** [comment]
This page is about 60% done :)

**Comment by jkresner** [comment]
A lot more UX is required later on in the flow... For now a hacky solution of making the title a link is in place.

![screen shot 2015-03-11 at 2 24 54 pm](https://cloud.githubusercontent.com/assets/979542/6607226/6f230bbe-c7fa-11e4-9e74-4070c4098d82.png)
