### ISSUE TITLE
Can´t reply to a reply

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#164]
have to reply to myself... which can get complicated if there´s a discussion here

![screen shot 2015-02-26 at 08 28 35](https://cloud.githubusercontent.com/assets/857253/6393656/a3543f02-bd91-11e4-973c-3e6dc37163e8.png)

**Comment by jkresner** [comment]
Same solution as to this one? https://github.com/airpair/airpair-com-v1-issue-tracker/issues/165

**Comment by jkresner** [comment]
Actually yeah, I opted not to allow replies to replies ... We'll see how people react
