### ISSUE TITLE
Permission to edit images

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#166]
Thanks for cleaning up the "Getting Started with Robolectric, JBehave and Maven" but can you give me permissions to do it myself - I would like to update the thumbnail image on this post for example

![screen shot 2015-02-26 at 08 52 03](https://cloud.githubusercontent.com/assets/857253/6394089/bf200f74-bd94-11e4-804f-657a96c1527e.png)

https://www.airpair.com/posts/preview/543cd28d512a8b0b00221cb2

http://i.imgur.com/4e1rZ1s.jpg

**Comment by jkresner** [comment]
Yeah - I think I know what was going on. You meant this link right?

https://www.airpair.com/posts/info/543cd28d512a8b0b00221cb2

And it was because you hadn't forked the project, which does not seem necessary?

**Comment by jkresner** [comment]
Fixed
