### ISSUE TITLE
Email verification link is not clickable

### ISSUE THREAD

**Issue by jseminck** [airpair/airpair-com-v1-issue-tracker#167]
Minor annoyance but the email verification link is not clickable, meaning I had to copy and paste it.

**Comment by jkresner** [comment]
on the user profile page?

**Comment by jseminck** [comment]
After signing up on the mail that I receive to verify my e-mail address: The link was not clickable on both my desktop mail client as well as my android phone mail client. Other links of sites have no problems. I'm not sure how the mails are generated and not sure if it is possible to force them to be a link but it would be a good but very minor improvement. :)

"Please make sure to verify your email using the following link:

https://www.airpair.com/me?verify=<...>

Happy pairing,"

**Comment by jkresner** [comment]
What clients do you have? Can you paste a screenshot?

We send the emails as both html and text versions... I'd have to look into it further.
