### ISSUE TITLE
Post link redirects to /posts/me

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#168]
Trying to click on these post links and they redirect me to /posts/me 

![screen shot 2015-02-26 at 21 22 01](https://cloud.githubusercontent.com/assets/857253/6406993/92bbde54-bdfd-11e4-88e7-6c08b49ca9a1.png)

**Comment by jkresner** [comment]
This is from the posts tag page?

**Comment by EllDudley** [comment]
Yep

**Comment by jkresner** [comment]
Fix thanks :)
