### ISSUE TITLE
Post editor will not load

### ISSUE THREAD

**Issue by egoebelbecker** [airpair/airpair-com-v1-issue-tracker#169]
I went to edit my post this morning and the editor will not load in my browser. Attached a screenshot in Firefox 36. I see the same thing in Chrome 40. 

Macbook Air with latest Yosemite.

![screen shot 2015-02-27 at 8 34 19 am](https://cloud.githubusercontent.com/assets/5241455/6413276/c92fb844-be5b-11e4-8b31-471ede1b292c.jpg)

**Comment by jkresner** [comment]
I think you'll be ok from now. Let me know if you have troubles.
