### ISSUE TITLE
Spell mistakes on Comp Page

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#170]
![screen shot 2015-02-27 at 09 06 29](https://cloud.githubusercontent.com/assets/857253/6414808/fb0eda44-be5f-11e4-997c-bdc3fba8e270.png)

Should read: AirPair is running a 100k Writing Competition over the next 3 months as part of a broader Social Authoring experiment. 

https://www.airpair.com/100k-writing-competition

**Comment by jkresner** [comment]
cool changes
