### ISSUE TITLE
want to change image... can't

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#171]
On top posts 2014 post:
https://www.airpair.com/posts/info/54d8fe3a5401050a0001b557

image - http://imgur.com/RKR9hG9.png
Tells me cannot update slug

![screen shot 2015-02-27 at 09 19 07](https://cloud.githubusercontent.com/assets/857253/6415041/bd56b2ba-be61-11e4-8610-85d0d6375a08.png)

**Comment by jkresner** [comment]
Fixed
