### ISSUE TITLE
Formatting of error message when save without commit message 

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#177]
When I hit save with commit message, this is what it looks like and the error doesn't go away when I enter a commit message

![screen shot 2015-03-01 at 14 12 22](https://cloud.githubusercontent.com/assets/857253/6432621/217e28b0-c01d-11e4-9075-22bf37d081a0.png)

**Comment by jkresner** [comment]
Fixed :)
