### ISSUE TITLE
use onunload to confirm closing the page when unsaved changes are pending

### ISSUE THREAD

**Issue by daniellmb** [airpair/airpair-com-v1-issue-tracker#18]
Need to add something like this:

```javascript
window.onbeforeunload = function() {
    if (pendingChanges) {
        return "Are you sure you want to leave?! You haven't saved your changes yet.";
    }
};
```

I lost some of my article when switching tabs, I accidentally clicked the close button when trying to toggle back to the markdown editor.

**Comment by jkresner** [comment]
:) 

![screen shot 2015-02-12 at 11 17 37 pm](https://cloud.githubusercontent.com/assets/979542/6183716/612d3568-b30d-11e4-8927-d76ded805bc6.png)

**Comment by daniellmb** [comment]
very nice!
