### ISSUE TITLE
Significant lag between updating markdown and updating preview in editor

### ISSUE THREAD

**Issue by dwanderton** [airpair/airpair-com-v1-issue-tracker#180]
There is a lag of approximately 3-4 seconds between updating the markdown in the editor and the preview content updating. As a user I expected this to be near instantaneous.

![preview_lag](https://cloud.githubusercontent.com/assets/3466284/6434443/d0c2b17c-c03d-11e4-8491-86ec351d7701.png)

Google Chrome Version 40.0.2214.115 (64-bit) - System info 
![system info](https://cloud.githubusercontent.com/assets/3466284/6434449/fdf582e6-c03d-11e4-8a1b-270d797b9e08.png)

**Comment by jkresner** [comment]
Lol read the first paragraph under Hello World.

**Comment by dwanderton** [comment]
lol got it! just take it as a comment of initial user expectation.
