### ISSUE TITLE
Editor Save status not apparent

### ISSUE THREAD

**Issue by dwanderton** [airpair/airpair-com-v1-issue-tracker#182]
As the preview is auto updating it is not always apparent if the current state of the document is saved. Also when Save is clicked there is no clear visual cue that the save has been successful - although the status in the top left is changed.

Suggestion: The top status bar should change to light red if the current document is not saved in its current state. On save the top status bar will transition to its current light turquoise color. Also as mentioned in #180 the save status has a delay of 3-4 seconds to update, although on save a delay is expected, on edit the user expectation is that the status alters to 'unsaved' almost instantly.

Example unsaved status bar:

![unsaved_example_status_bar](https://cloud.githubusercontent.com/assets/3466284/6434613/23d92316-c041-11e4-8939-a690a525bf65.png)

**Comment by jkresner** [comment]
Implemented awesome :)
