### ISSUE TITLE
Editor: With unsaved changes, on attempted submit 5 dialog boxes are triggered

### ISSUE THREAD

**Issue by dwanderton** [airpair/airpair-com-v1-issue-tracker#186]
If the user clicks submit when unsaved changes are present, 5 dialogs are triggered informing the user. One after the other. Tested in Chrome Version 40.0.2214.115 (64-bit). Mac OSX 10.10

![dialogue_box_number_2](https://cloud.githubusercontent.com/assets/3466284/6436260/6e2a0ce4-c061-11e4-8410-11afcef154bc.png)

**Comment by jkresner** [comment]
This was expecting behavior. What are you suggesting?

**Comment by dwanderton** [comment]
Only one dialog box should be triggered (assumed expected behaviour). Each time 'OK' is clicked another box appears. (5 boxes in total).

**Comment by jkresner** [comment]
Fix in next deploy
