### ISSUE TITLE
Publish Page: Small CSS issue - tags and notice overlap

### ISSUE THREAD

**Issue by dwanderton** [airpair/airpair-com-v1-issue-tracker#187]
When the post under community review is hovered over the text notice and post tags overlap.

Possible solution: align notice text to bottom of image container.

![slight_overlap](https://cloud.githubusercontent.com/assets/3466284/6436356/e273510e-c062-11e4-8098-b535f1c631c9.png)

**Comment by jkresner** [comment]
Fixed in next deploy
