### ISSUE TITLE
Invite to review: Tweet url incomplete

### ISSUE THREAD

**Issue by dwanderton** [airpair/airpair-com-v1-issue-tracker#188]
The url which is in the tweet only contains the path and not the domain - and will not link as intented. Also given the possible lengths of the uris it may be beneficial to shorten the urls prior to being added to the tweet.

![tweet_url](https://cloud.githubusercontent.com/assets/3466284/6436393/67a8c340-c063-11e4-8469-08ef61ac5b50.png)

**Comment by jkresner** [comment]
Fixed thanks :)
