### ISSUE TITLE
Post display: Large number of headers cause overlap in footer

### ISSUE THREAD

**Issue by dwanderton** [airpair/airpair-com-v1-issue-tracker#189]
If a post has a large number of headers these headers are displayed with a vertical scroll on the right side of the screen. However when the user reaches the bottom of the post, the container for the headers does not shrink and instead flows behind the section of tags. 

This means that the headers are visible under the tags section.

![header_overflow](https://cloud.githubusercontent.com/assets/3466284/6436439/3054a7c8-c064-11e4-8a86-2598dd42d761.png)

**Comment by jkresner** [comment]
You would only see this when you are the author and the post have no reviews ... :)
