### ISSUE TITLE
Use side-by-side layout for the markdown editor

### ISSUE THREAD

**Issue by daniellmb** [airpair/airpair-com-v1-issue-tracker#19]
I think the way https://ghost.org and http://dillinger.io layout the page is much more productive then the current airpair v1 layout.

## ghost
![image](https://cloud.githubusercontent.com/assets/108018/4959080/139284e2-66b5-11e4-9409-7024ef8d09fb.png)

## dillinger
![dillinger](https://cloud.githubusercontent.com/assets/108018/4931652/f086311c-657c-11e4-833e-ece1b11acc4e.png)

## airpair v1
![airpair](https://cloud.githubusercontent.com/assets/108018/4931656/10c00020-657d-11e4-89ae-e83d0be1c086.png)

**Comment by jkresner** [comment]
![screen shot 2015-01-30 at 4 16 36 pm](https://cloud.githubusercontent.com/assets/979542/5987856/feaa7e10-a8f7-11e4-82d9-feae7dfa7449.png)

Hope you like it!

**Comment by daniellmb** [comment]
Excellent work, the editor looks much better! However, it suffers from the same usability issue as the one I submitted for Dillinger. https://github.com/joemccann/dillinger/issues/248 Slowing down rerendering the left side with debounce will help.

**Comment by jkresner** [comment]
Actually the old editor had that feature and I just haven't had time to put it back yet. It will be in there this week.
