### ISSUE TITLE
Editor: XSS vulnerability

### ISSUE THREAD

**Issue by dwanderton** [airpair/airpair-com-v1-issue-tracker#190]
As markdown script tags are rendered it is possible to inject malicious code into the airpair posts.

![xss vulnerability](https://cloud.githubusercontent.com/assets/3466284/6436499/8a47020c-c065-11e4-9167-e3ceaae34b59.png)

**Comment by jkresner** [comment]
We need to allow script execution, so we'll just have to make sure these don't get through review.
