### ISSUE TITLE
Requests: don't see a "Delete" (or "Remove") button

### ISSUE THREAD

**Issue by spookiecookie** [airpair/airpair-com-v1-issue-tracker#191]
On the Requests page I don't see a "Delete" or a "Remove" button to remove a request. How to remove a request?:)

![image](https://cloud.githubusercontent.com/assets/5195215/6441404/2b4a048a-c0f0-11e4-8bcd-adbec1a7e6b4.png)

**Comment by jkresner** [comment]
You can only delete unfinished requests. At some near point we'll implement an archive feature.

**Comment by spookiecookie** [comment]
ok:)
