### ISSUE TITLE
TOC bug with headers in code snippets

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#193]
From Mark Shust - https://www.airpair.com/firebase/posts/making-a-keenio-dashboard-realtime-by-integrating-it-with-firebase--d3js

I did notice a bug with the table of contents that shows to the right of the blog post. You'll notice two headings showing there that shouldn't be:

- Dashboard
- Average Cost By Gender

Those are coming from header tags... but from header tags within code snippets. Just thought I'd let you know.

**Comment by jkresner** [comment]
Think I got it!

![screen shot 2015-03-11 at 4 33 40 pm](https://cloud.githubusercontent.com/assets/979542/6609251/66d04b9a-c80c-11e4-9afd-4133a992cec1.png)
