### ISSUE TITLE
Got message "Cannot reply to this request, as it is not active"

### ISSUE THREAD

**Issue by AndyObtiva** [airpair/airpair-com-v1-issue-tracker#196]
Got message "Cannot reply to this request, as it is not active"
Here is the request: https://www.airpair.com/review/54f722223696cb0c00dfc4d1

It's possible it got accepted by someone else. It would be nice to show that before I start composing a reply to it to avoid wasting my time if it was taken already.

Thanks...

**Comment by jkresner** [comment]
Duplicate - will be fixing in in the next 24 hours 

https://github.com/airpair/airpair-com-v1-issue-tracker/issues/86

**Comment by jkresner** [comment]
:) 

https://github.com/airpair/airpair-com-v1-issue-tracker/issues/133

**Comment by AndyObtiva** [comment]
Thanks for the link Jonathan. Looking forward to experiencing the fix soon. 

Andy
