### ISSUE TITLE
Code formatting issue From Nic Raboy

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#198]
It seems not every GitHub code fence is being picked up.  JavaScript seems to work, but things like XHTML and Shell don’t seem to get picked up.  According to the linguistic file those should be valid options.  Any ideas?  I have a lot of HTML code that will look sketchy without proper formatting.

**Comment by nraboy** [comment]
Bash works, but I should be able to use ZSH, SH, or Shell.  XML, HTML, and XHTML don't work either.

Thanks,

**Comment by jkresner** [comment]
You need to say "markup"

**Comment by nraboy** [comment]
That wasn't as obvious as I had hoped, but it worked.  Thanks!

**Comment by jkresner** [comment]
Agreed @nraboy :(

@EllDudley  can you add it to the author FAQ?
