### ISSUE TITLE
Change text to compose (instead of composeio)

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#200]
![screen shot 2015-03-04 at 16 14 28](https://cloud.githubusercontent.com/assets/857253/6494729/942668a0-c289-11e4-8372-143c3090986d.png)

**Comment by jkresner** [comment]
Creating github issues for these is a bit overboard :). Stick em in trello.

**Comment by EllDudley** [comment]
Its the best way to get in touch with you - you always respond :) trello
can get buried.

**Comment by jkresner** [comment]
I look at trello 5x more than I look at github issues :)
ᐧ

On Wed, Mar 4, 2015 at 3:25 PM, Ellen Dudley <notifications@github.com>
wrote:

> Its the best way to get in touch with you - you always respond :) trello
> can get buried.
> El mar 4, 2015 4:22 PM, "Jonathon Kresner" <notifications@github.com>
> escribió:
>
> > Creating github issues for these is a bit overboard :). Stick em in
> trello.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/airpair/airpair-com-v1-issue-tracker/issues/200#issuecomment-77263056
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/airpair/airpair-com-v1-issue-tracker/issues/200#issuecomment-77263664>
> .
>



-- 
Jonathon Kresner
about.me <http://about.me/jonathonkresner> | hackerpreneurialism
<http://hackerpreneurialism.com> | @hackerpreneur
<http://twitter.com/hackerpreneur>
