### ISSUE TITLE
Adding C# to stack results in c%23

### ISSUE THREAD

**Issue by rogier21** [airpair/airpair-com-v1-issue-tracker#202]
The screenshot will speak for itself :)
![screenshot_1](https://cloud.githubusercontent.com/assets/1142915/6536903/d21de148-c40e-11e4-9a7f-fd91d4f6a967.png)

**Comment by MaxHershey** [comment]
I was able to duplicate this issue as well.

**Comment by jkresner** [comment]
@rogier21 @MaxHershey closing as duplicate:

https://github.com/airpair/airpair-com-v1-issue-tracker/issues/96

Each of your accounts have been credited $10
