### ISSUE TITLE
Tried to update my post without success

### ISSUE THREAD

**Issue by gsans** [airpair/airpair-com-v1-issue-tracker#204]
I have added few changes on my post but could not synch from the website so

1) I cloned the repository locally and merged. All looks good in github now. post.md includes all changes so it's good to go. The issue is that changes are not public. Is that the way it should be?

2) As a side effect, now I can't edit the post from the editor nor fork it.

This is the post: https://www.airpair.com/jasmine/posts/javascriptintegrating-jasmine-with-requirejs-amd

Thanks!
Gerard.

**Comment by jkresner** [comment]
1) Yes, an editor is required to sync posts that are published

2) I think the issues is your token has expired and the UI doesn't have a nice way to deal with authoring ... I'll look into it thanks.
