### ISSUE TITLE
new signup: did not record stack choices

### ISSUE THREAD

**Issue by jhund** [airpair/airpair-com-v1-issue-tracker#208]
I signed up for a new account. On the profile page I selected three technologies for my stack. I submitted the form successfully, however when I went back to my profile page, it did not include any items in my stack. I had to re-enter them again. Then it worked.

**Comment by jkresner** [comment]
Did you loose all your details, or just the tags?

**Comment by jhund** [comment]
Just the tags for the 3 technologies that are required to get going. All the other fields were ok.

**Comment by jkresner** [comment]
Still seeing this on our newer experts portal?

https://consult.airpair.com/profile
