### ISSUE TITLE
Error collecting v1session upon login

### ISSUE THREAD

**Issue by mjmj** [airpair/airpair-com-v1-issue-tracker#209]
I logged in with google and received the message 'Error collecting v1session' above the connect4 image. Reloading the page refreshed everything and displayed the proper image.

Gmail login
Google Chrome 41.0.2272.76 (64-bit)
Mac 10.9.5

**Comment by jkresner** [comment]
This happens when we deploy and the app restarts. I've had about 3 cracks around stopping this error, but alas - I cannot figure it out :)
