### ISSUE TITLE
The style seems to be broken

### ISSUE THREAD

**Issue by gosuri** [airpair/airpair-com-v1-issue-tracker#210]
![screen shot 2015-03-10 at 2 06 13 pm](https://cloud.githubusercontent.com/assets/70293/6585531/ab7782e6-c72f-11e4-9908-30382ba6ffb6.png)
https://www.airpair.com/aws/posts/ntiered-aws-docker-terraform-guide

**Comment by jkresner** [comment]
Need to do a better job than this at some point :)

![screen shot 2015-03-10 at 5 04 32 pm](https://cloud.githubusercontent.com/assets/979542/6587898/8d913c00-c747-11e4-9904-eb7e248800dc.png)
