### ISSUE TITLE
No automatic "sync my post please"

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#211]
Nic Raboy updated his post but I didn't receive an email notification in team@airpair to sync it. Is that email notification still being sent? 

![screen shot 2015-03-10 at 19 06 25](https://cloud.githubusercontent.com/assets/857253/6588516/94446d22-c758-11e4-81dd-6acddcac05ba.png)

**Comment by jkresner** [comment]
They manually email you. It's not an automated feature.
