### ISSUE TITLE
Article Rating Rounding

### ISSUE THREAD

**Issue by RichMcL** [airpair/airpair-com-v1-issue-tracker#213]
When viewing an article, the average rating does not have a reasonable cut-off point for a decimal point. See attached image.
![image](https://cloud.githubusercontent.com/assets/667290/6589167/30fe0524-c772-11e4-95a6-0457d9d39ceb.png)

**Comment by jkresner** [comment]
Thanks fixed. Your account has been credit $10 :)

![screen shot 2015-03-11 at 5 36 31 pm](https://cloud.githubusercontent.com/assets/979542/6609897/3be1e764-c815-11e4-97c6-01bf8c1a3851.png)
