### ISSUE TITLE
Cannot reply to this request, as it is not active

### ISSUE THREAD

**Issue by chip** [airpair/airpair-com-v1-issue-tracker#214]
I just received the `Cannot reply to this request, as it is not active` for this request:
https://www.airpair.com/review/5500b37ba0a7a80c0047643d

However, each time I reload, it allows me to fill out the form. There is nothing in the UI that indicates it is not active.

**Comment by jkresner** [comment]
Finally fixed this... sorry for any inconvenience. If you'd like to get involved in making the expert side of AirPair better and potentially fix bugs, check out:

https://github.com/airpair/experts.airpair.com

![screen shot 2015-03-12 at 1 19 06 pm](https://cloud.githubusercontent.com/assets/979542/6627277/6331e760-c8ba-11e4-94d9-a632dc87d056.png)
