### ISSUE TITLE
Routing issue with breadcrumbs

### ISSUE THREAD

**Issue by RichMcL** [airpair/airpair-com-v1-issue-tracker#217]
When on https://www.airpair.com/posts/in-community-review and navigating to https://www.airpair.com/posts through the breadcrumbs, the content does not load
![routing](https://cloud.githubusercontent.com/assets/667290/6640802/0ccfae5a-c970-11e4-949a-5d2a0d791912.gif)

**Comment by jkresner** [comment]
Thanks @RichMcL will be fixed in the next deploy this morning!
