### ISSUE TITLE
Posts using a youtube video as main asset puts YT link in img src 

### ISSUE THREAD

**Issue by dwanderton** [airpair/airpair-com-v1-issue-tracker#219]
Page load delays and image missing caused by browser requests to youtube urls in img src. should be a request to youtube video thumbnail.

As seen in https://www.airpair.com/posts/review

![img_src_is_youtube_url](https://cloud.githubusercontent.com/assets/3466284/6643364/cbd565ae-c968-11e4-8794-6be3de22ac48.png)

**Comment by jkresner** [comment]
Duplicate https://github.com/airpair/airpair-com-v1-issue-tracker/issues/203
