### ISSUE TITLE
Syntax highlighting on code blocks missing for html in Post Editor Preview

### ISSUE THREAD

**Issue by dwanderton** [airpair/airpair-com-v1-issue-tracker#221]
HTML syntax highlighting appears not to be working

![html_syntax highlighting](https://cloud.githubusercontent.com/assets/3466284/6647877/7e34927a-c990-11e4-9c3f-c3a92cc80e07.png)

**Comment by jkresner** [comment]
The syntax is 

```markdown
<p>Test</p>
```

Please add to the authoring FAQ

**Comment by dwanderton** [comment]
```markdown
<p> test</p>
<layout> hello </layout>
```

**Comment by dwanderton** [comment]
Please re-open issue

![screen shot 2015-03-13 at 17 08 42](https://cloud.githubusercontent.com/assets/3466284/6649275/a73d9140-c9a3-11e4-9fba-4c6fa120decb.png)

**Comment by jkresner** [comment]
Sorry this is meant to be "markup" no "markdown"
