### ISSUE TITLE
Explain to authors not to merge edit branch into master

### ISSUE THREAD

**Issue by jkresner** [airpair/airpair-com-v1-issue-tracker#224]
> Thanks for the tip. I had thought syncing my changes after publishing would
be similar to when my post was in review mode so I was trying to find a way
that I could do the sync myself.
> One of the links on the sync page in AirPair sent me to GitHub, which had a
fairly predominant button at the top that made me think I had to do a pull
and merge.
> I think a warning/explanation at the top of AirPair's sync page probably
would have kept me from making that mistake. Maybe it could be added there
if this is a common problem?

**Comment by kytwb** [comment]
:+1:

**Comment by jkresner** [comment]
Hopefully a few hints along the workflow and the new README format will stop this from happening. Guess we'll see in the next few days :)
