### ISSUE TITLE
Not a string or buffer

### ISSUE THREAD

**Issue by dfguo** [airpair/airpair-com-v1-issue-tracker#228]
got this error when booking

**Comment by jkresner** [comment]
@dfguo did you mean to book 4 times? I will look into this later this week, for now I've stopped the app crashing, but probably an image will be missing somewhere.

**Comment by dfguo** [comment]
no, i only want to book once, but the app keeps on crashing so i retried. Please refund.

**Comment by jkresner** [comment]
Will take care of in the morning. Thanks@!

**Comment by jkresner** [comment]
Implemented single click only login on the submit button so this won't be able to happen anymore.
