### ISSUE TITLE
"Cannot update expert without username"

### ISSUE THREAD

**Issue by jasonswett** [airpair/airpair-com-v1-issue-tracker#232]
I tried to update my expert profile and it gave me an error that said "Cannot update expert without username". As far as I could tell, all fields, including username, were filled validly.

**Comment by jkresner** [comment]
I think what might be happening is there's a feature that's auto suggesting a username from your github or twitter account, but it's not actually triggering a save...

**Comment by jasonswett** [comment]
If it helps to know, I was eventually able to work around the problem by backspacing a few characters of my username, then re-typing them.

And also if it helps to know, this bug (until I figured out how to get around it) prevented me from updating my profile which prevented me from accepting a request that was matched to me.

**Comment by jkresner** [comment]
Thanks, have seen 3 people do this today, just a matter of when to deal with it in the queue :)

**Comment by jkresner** [comment]
Ok think I've fixed this one. Thanks!!@
