### ISSUE TITLE
twitter links on profiles not working - goes to twitter.com

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#233]
https://www.airpair.com/javascript/posts/speed-up-your-angular-apps-and-get-rid-of-sasqwatches

https://www.airpair.com/javascript/complete-expressjs-nodejs-mongodb-crud-skeleton
![screen shot 2015-03-16 at 20 47 49](https://cloud.githubusercontent.com/assets/857253/6680496/bfaa269a-cc1d-11e4-8e98-1aff40abd602.png)

**Comment by jkresner** [comment]
Duplicate https://github.com/airpair/airpair-com-v1-issue-tracker/issues/231
