### ISSUE TITLE
wordwrap not wrapping inline code at correct breakpoint on posts

### ISSUE THREAD

**Issue by dwanderton** [airpair/airpair-com-v1-issue-tracker#239]
As seen on: https://www.airpair.com/posts/review/54f6eca08438550c00e98469

![screen shot 2015-03-18 at 15 55 36](https://cloud.githubusercontent.com/assets/3466284/6721184/84cfa926-cd87-11e4-93f6-a28ea09debaf.png)

**Comment by jkresner** [comment]
Please use multi line code syntax

**Comment by dwanderton** [comment]
Header on https://www.airpair.com/posts/review/55084b12ac950a0c00c2b104 over lapping contents. same issue? 
![screen shot 2015-03-18 at 21 04 44](https://cloud.githubusercontent.com/assets/3466284/6724316/9898d574-cdb2-11e4-9fab-cb642e9baaa4.png)

**Comment by jkresner** [comment]
Probably won't fix for a while. This is not a reasonable heading and we've not got much time to waste on this stuff.
