### ISSUE TITLE
Content headers on blog post wrap to top of container (assumed due to length of headings)

### ISSUE THREAD

**Issue by dwanderton** [airpair/airpair-com-v1-issue-tracker#240]
As seen on: https://www.airpair.com/posts/review/5508ca751a2d210c00cef5fd

![screen shot 2015-03-18 at 17 14 51](https://cloud.githubusercontent.com/assets/3466284/6722145/985ea522-cd92-11e4-9cde-d69975c032b3.png)

**Comment by jkresner** [comment]
This is not a bug the headers are wrong.

**Comment by dwanderton** [comment]
Can you clarify what wrong means?

**Comment by jkresner** [comment]
The markup is full of h1s
