### ISSUE TITLE
Scrolling code box in Post Editor causes code to escape into surrounding content

### ISSUE THREAD

**Issue by dwanderton** [airpair/airpair-com-v1-issue-tracker#243]
probably low priority.

As seen at:  https://www.airpair.com/posts/edit/5507f1c7ac950a0c00c2a191 using Google Chrome Version 41.0.2272.89 (64-bit)

![screen shot 2015-03-18 at 20 03 14](https://cloud.githubusercontent.com/assets/3466284/6723797/2a494c14-cdaa-11e4-8bd8-04644f4fd520.png)

**Comment by jkresner** [comment]
Can we skip the low priority ones for now and come back to them in a 4-6
weeks :)
ᐧ

On Wed, Mar 18, 2015 at 8:05 PM, David Anderton <notifications@github.com>
wrote:

> probably low priority.
>
> As seen at: https://www.airpair.com/posts/edit/5507f1c7ac950a0c00c2a191
> using Google Chrome Version 41.0.2272.89 (64-bit)
>
> [image: screen shot 2015-03-18 at 20 03 14]
> <https://cloud.githubusercontent.com/assets/3466284/6723797/2a494c14-cdaa-11e4-8bd8-04644f4fd520.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/airpair/airpair-com-v1-issue-tracker/issues/243>.
>



-- 
Jonathon Kresner
about.me <http://about.me/jonathonkresner> | hackerpreneurialism
<http://hackerpreneurialism.com> | @hackerpreneur
<http://twitter.com/hackerpreneur>
