### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by kytwb** [airpair/airpair-com-v1-issue-tracker#248]
I noticed a bug on my article [Efficient development workflow using Git submodules and Docker Compose](https://www.airpair.com/docker/posts/efficiant-development-workfow-using-git-submodules-and-docker-compose). A picture's worth a thousand words, so here you go:

![Table of Contents issue](http://i.imgur.com/Z0EFjQA.png)

**Comment by jkresner** [comment]
Thanks, there's lots of little use cases like this. We will look eventually, for now most development on for post related features is on hold till late April as other parts of the site are in dire need of attention. Is there a way to show the site in the code editor perhaps with _ instead of - ?

**Comment by kytwb** [comment]
?!

**Comment by jkresner** [comment]
It thinks it's a heading

Name
------------

**Comment by kytwb** [comment]
Ah, didn't understand the first part of your sentence. I'll try to replace `_` with `-`.
