### ISSUE TITLE
Alter Content Security Policy to allow embeded tweets on Posts

### ISSUE THREAD

**Issue by dwanderton** [airpair/airpair-com-v1-issue-tracker#259]
As seen with:
https://www.airpair.com/posts/review/550b7541bbbbef0c004b37ea

With CSP in review:
![screen shot 2015-03-25 at 12 15 48](https://cloud.githubusercontent.com/assets/3466284/6833243/bfecef6c-d2e8-11e4-92c5-6afaac58353e.png)

In edit:
![screen shot 2015-03-25 at 12 17 07](https://cloud.githubusercontent.com/assets/3466284/6833265/e56ef244-d2e8-11e4-9fca-835bfbd2835d.png)

**Comment by jkresner** [comment]
Need you to stop focusing on this stuff and get the content machine where it needs to be.
