### ISSUE TITLE
Problem booking

### ISSUE THREAD

**Issue by ccheever** [airpair/airpair-com-v1-issue-tracker#267]
https://www.dropbox.com/s/cbws3v6lemut9uj/Screenshot%202015-04-07%2016.20.23.png?dl=0

Credit card dropdown only contains mysterious "undefined's card" and no option to choose a different or new one.

Trying to book causes a mysterious error message.

**Comment by jkresner** [comment]
Deploying fix very shortly. Cheers.

**Comment by jkresner** [comment]
Alternatively, you can delete your existing card (stripe info), here:

https://www.airpair.com.com/billing

And re-add your card (as a braintree token).

**Comment by ccheever** [comment]
That doesn't work either actually.

https://www.dropbox.com/s/bqkmlu3oauvij9y/Screenshot%202015-04-07%2017.16.04.png?dl=0

**Comment by jkresner** [comment]
I see - just making a database backup before deploy bit slow from aus :)... Ping you when a fix is live

**Comment by jkresner** [comment]
Any luck booking in the end? How was your session :) ?
