### ISSUE TITLE
Website Sign-up issue

### ISSUE THREAD

**Issue by issamux** [airpair/airpair-com-v1-issue-tracker#268]
Hi,

I've create an account  and receive an email to validate my email ,i guess the link in email was wrong:
https://www.airpair.com/me/password?token=
because the token param was empty , i re-clicked to send an other email validation, this time the link
https://www.airpair.com/me?verify="" simply doesn't work.

Any solution to be able to create account and join you're community :)

**Comment by jkresner** [comment]
Are you still having troubles signing up? I believe you already inputted a password and the wrong code path was being executed asking you to give your password again. You could also login with google and it will connect your account, or use Fogotten password.

**Comment by jkresner** [comment]
Fix deployed cheers
