### ISSUE TITLE
"Must migrate expert profile to reply"

### ISSUE THREAD

**Issue by ErikEJ** [airpair/airpair-com-v1-issue-tracker#269]
Yes, understood, but how?

**Comment by jkresner** [comment]
Did you already full in this:

https://www.airpair.com/be-an-expert

**Comment by ErikEJ** [comment]
Yes, and I receive requests from you as well.

Mvh / Regards


Erik Ejlskov Jensen
http://twitter.com/erikej
 
Date: Fri, 17 Apr 2015 01:52:20 -0700

**Comment by jkresner** [comment]
I'm away for the weekend, I'll take a look at your account Monday maybe
sooner. Thanks, Jonathon

On Friday, April 17, 2015, Erik Ejlskov Jensen <notifications@github.com>
wrote:

> Yes, and I receive requests from you as well.
>
> Mvh / Regards
>
>
> Erik Ejlskov Jensen
> http://twitter.com/erikej
>
> Date: Fri, 17 Apr 2015 01:52:20 -0700
> From: notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> To: airpair-com-v1-issue-tracker@noreply.github.com
> <javascript:_e(%7B%7D,'cvml','airpair-com-v1-issue-tracker@noreply.github.com');>
> CC: ejlskov@hotmail.com
> <javascript:_e(%7B%7D,'cvml','ejlskov@hotmail.com');>
> Subject: Re: [airpair-com-v1-issue-tracker] "Must migrate expert profile
> to reply" (#269)
>
> Did you already full in this:
>
>
> https://www.airpair.com/be-an-expert
>
>
> —
> Reply to this email directly or view it on GitHub.
>
>
>
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/airpair/airpair-com-v1-issue-tracker/issues/269#issuecomment-93954928>
> .
>


-- 
*Jonathon Kresner*
*Co-founder, CEO*
@AirPair <http://twitter.com/airpair> | *airpair.com
<http://www.airpair.com>*
@hackerpreneur <http://twitter.com/hackerpreneur>

**Comment by jkresner** [comment]
I've twice now seen mongo not enforcing unique key on userId for experts and creating multiple profiles. Diagnosing and fixing this now.

**Comment by jkresner** [comment]
I've cleaned up some issues around multiple profiles that seem to have existed for almost 12 months, please reopen if you are still seeing hurdles. I think you're good now.
