### ISSUE TITLE
Changing pipeline status causes error

### ISSUE THREAD

**Issue by sirramongabriel** [airpair/airpair-com-v1-issue-tracker#270]
On these two reqeusts:

1. https://www.airpair.com/adm/pipeline/55372296336a0a110075636d
2. https://www.airpair.com/adm/pipeline/552aa4cfc09fdd110017aeab

When changing status of request, the error below triggers.

![screen shot 2015-04-22 at 9 44 38 am](https://cloud.githubusercontent.com/assets/1680692/7275925/9e7aa868-e8d4-11e4-9000-4e3cb634c976.jpg)

**Comment by jkresner** [comment]
Seems to be fixed now.
