### ISSUE TITLE
Can't see most recently published posts on /posts

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#271]
https://www.airpair.com/javascript/posts/a-year-using-ionic-to-build-hybrid-applications has been published today. Can't see it on https://www.airpair.com/posts. 

![screen shot 2015-04-23 at 19 40 52](https://cloud.githubusercontent.com/assets/857253/7310386/b0f63b34-e9f0-11e4-8f82-291ff770cb9a.png)

**Comment by jkresner** [comment]
Posts are now cached and the app requires a restart. It's there now.
