### ISSUE TITLE
"Do you want this airpair" failed to post

### ISSUE THREAD

**Issue by EricRohlfs** [airpair/airpair-com-v1-issue-tracker#274]
Trying to respond to a request, and the submit failed to post.

**Comment by EricRohlfs** [comment]
It seems the whole site had an issue, I just posted, so I'll close this issue.

**Comment by jkresner** [comment]
We've had some funny behavio with our mongo host over the last few weeks that we're trying to figure out. Sorry for inconvinience. Jonathon
