### ISSUE TITLE
Tried to Book, got an error

### ISSUE THREAD

**Issue by blakedallen** [airpair/airpair-com-v1-issue-tracker#276]
The page seems to be timing out for me... alot. 

Normally it's not an issue, but this time I tried to book an Air Pair and I got a blank screen. 

Chrome 42.0.2311.135 (64-bit), Mac OSX Yosemite, 13.5 mbs down, .75 up

**Comment by jkresner** [comment]
We never figured out what was causing this :(, but our white outs have stopped for now.

**Comment by jkresner** [comment]
We now believe someone in India was running an automation script to try and with our content competition :/
