### ISSUE TITLE
Accessing /about page flashes error

### ISSUE THREAD

**Issue by cmitz** [airpair/airpair-com-v1-issue-tracker#334]
I clicked on the logo at the left-top of a post-page after trying to give 5 stars while I was not logged in. I was directed to the /about page and this error flashed. Perhaps my issue title is not descriptive enough, but I think this small error can be fixed :)
![Screenshot](http://i.imgur.com/YzDV67I.png)

**Comment by jkresner** [comment]
Page no longer exists :)
