### ISSUE TITLE
All links open in the same window as the article

### ISSUE THREAD

**Issue by ryansb** [airpair/airpair-com-v1-issue-tracker#337]
I don't have statistics, but I think most readers of technical articles prefer not to lose their place when they click an in-article link. Right now, any markdown link opens in the same window as the article; it would be better if they opened as tabs.

Adding a `target=` property to links would make them open in new tabs.

**Comment by jkresner** [comment]
markdown doesn't have this feature. they can always rightclick and open in new window. Alternatively you can substitute your markdown for html in that point.
