### ISSUE TITLE
`+` in email address breaks verification

### ISSUE THREAD

**Issue by alxndr** [airpair/airpair-com-v1-issue-tracker#34]
Email verification breaks when trying to verify an email address with a plus sign (`+`) in it. The signup process allows you to enter the email with the plus sign, and the email comes through successfully, but when clicking on the "verify" link in the email, the AirPair page shows an error below the email input box, with the content: "[object Object] failed"

**Comment by jkresner** [comment]
I'm not sure this had to do with a + in the email. Would you kindly test this again and I will be happy to credit you a second $10 to your account.

**Comment by alxndr** [comment]
Can't log in right now; I believe I changed my account's email address to remove the plus sign, but it doesn't like my password, and when I try to send a password reset email I get this error in the browser:

    exception: E11000 duplicate key error index: app[########].users.$email_1 dup key: { : "[MY EMAIL]" }

**Comment by jkresner** [comment]
Ok sorry, this should be fixed. Please try on more time and I will credit your account $20 :P

**Comment by alxndr** [comment]
Same behavior

**Comment by jkresner** [comment]
Still no huh... ?

**Comment by jkresner** [comment]
Very sorry... what are the exact steps? You are currently logged off and you are resetting your password with the email address alxndr@gmail.com?

**Comment by jkresner** [comment]
Ok, I have the error locally. Will fix in next 10 mins.

**Comment by jkresner** [comment]
Yeah this was a doozy. You have one account created by local credentials (email / password) and another account created with google login. Both have the same email, but the password reset looks for both cases. The data is not meant to get into this state, but with the email verifications bugs this was probably possible. Some time will have to be spent making sure this does not happen to more users in the future, but it might be low on the priority list right now. For now I've deleted one of your accounts and you are good to go!

**Comment by jkresner** [comment]
Apologies, I had to wipe the tags you chose to make up your stack.

**Comment by alxndr** [comment]
Okay, sorry about all that account nonsense!
