### ISSUE TITLE
Trying to suggest a new time, received an error.

### ISSUE THREAD

**Issue by sparkyspider** [airpair/airpair-com-v1-issue-tracker#346]
https://www.airpair.com/bookings/559e3459659e241100e36ff4
Time[1436862600000] already suggested as an option for Booking[559e3459659e241100e36ff4]

**Comment by sparkyspider** [comment]
I'd recommend using 2 input boxes (one for date and one for time). I found the interaction confusing.

**Comment by jkresner** [comment]
I experience this bug this morning :) The page isn't refreshing after you
add the time :)

ᐧ

On Thu, Jul 9, 2015 at 2:51 AM, Mark van Wyk <notifications@github.com>
wrote:

> I'd recommend using 2 input boxes (one for date and one for time). I found
> the interaction confusing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/airpair/airpair-com-v1-issue-tracker/issues/346#issuecomment-119893046>
> .
>



-- 
*Jonathon Kresner*
*Co-founder, CEO*
@AirPair <http://twitter.com/airpair> | *airpair.com
<http://www.airpair.com>*
@hackerpreneur <http://twitter.com/hackerpreneur>

**Comment by jkresner** [comment]
Should be fixed now thank you!
