### ISSUE TITLE
Tag page returning error

### ISSUE THREAD

**Issue by kevgathuku** [airpair/airpair-com-v1-issue-tracker#347]
When trying to load a page such as https://www.airpair.com/posts/tag/javascript or any other tag, an error is displayed prompting the user to report the issue
Here is a screenshot of the error page
![tag_error](https://cloud.githubusercontent.com/assets/3721994/8655757/f8db906c-299b-11e5-91b3-a997219d793d.png)

**Comment by jkresner** [comment]
Fixed. Thank you kindly for reporting!
