### ISSUE TITLE
Error when I clicked on 'For' in the payments page

### ISSUE THREAD

**Issue by gosuri** [airpair/airpair-com-v1-issue-tracker#349]
Reproduce:

1. Login - I'm an expert
2. https://www.airpair.com/payouts
3. Click on any cell in the 'For' column
4. Error (on page https://www.airpair.com/bookings/550a23f8e414bc0c0094b2c8)
<img width="1006" alt="screen shot 2015-07-16 at 13 47 51" src="https://cloud.githubusercontent.com/assets/70293/8734814/559a9a60-2bc1-11e5-87e3-e256e1d59d73.png">

**Comment by jkresner** [comment]
Fixed thanks boss.
