### ISSUE TITLE
Received error on slack group creation

### ISSUE THREAD

**Issue by tmbeihl** [airpair/airpair-com-v1-issue-tracker#351]
{"id":"U03ME5Q7X","name":"123peterkim","deleted":false,"real_name":"Peter Kim","tz_label":"Pacific Daylight Time","profile":{"email":"123peterkim@gmail.com"}} |||| {"id":"U03S09JGE","name":"tmbeihl","deleted":false,"real_name":"Thomas Beihl","tz_label":"Eastern Daylight Time","profile":{"email":"tmbeihl@tmbeihl.com"}} showed up as a error message. Looks like slack was created though. I was given the option to create a group. See attached image.
![image](https://cloud.githubusercontent.com/assets/982144/8808778/9d4dc37e-2fb2-11e5-88c6-7bd0093b3490.png)

**Comment by jkresner** [comment]
I think I was setting up the room in admin at the same time. Next time I'll let you do the non-admin flow to see if it's broken (probably is)
