### ISSUE TITLE
Snippet code got replaced with garbish data

### ISSUE THREAD

**Issue by kytwb** [airpair/airpair-com-v1-issue-tracker#352]
See the snippet codes in "[Efficient development workflow using Git submodules and Docker Compose](https://www.airpair.com/docker/posts/efficiant-development-workfow-using-git-submodules-and-docker-compose)".

**Comment by jkresner** [comment]
Turned out to be cloudflare network security obscufating the email addresses. I've added a rule to exclude your post as an exception. If lots of posts experience the issue I'll look at turning of the feature.
