### ISSUE TITLE
Edit stack does not work

### ISSUE THREAD

**Issue by antoinepairet** [airpair/airpair-com-v1-issue-tracker#353]
Editing the stack is currently not working. Clicking on either `edit` or `Add technologies` does not do anything. Conclusion `openStack()` is not defined on the `scope`.

![screen shot 2015-07-31 at 17 20 51](https://cloud.githubusercontent.com/assets/5238592/9010659/88c17790-37a8-11e5-850d-ce11711701b0.png)

![screen shot 2015-07-31 at 17 21 23](https://cloud.githubusercontent.com/assets/5238592/9010667/9af42872-37a8-11e5-8a8d-54055b0aa28e.png)

**Comment by jkresner** [comment]
Stack was always intended to drive personalization of the site. These features are not yet completed, so I've decided to remove stack (though the fix was simple) and we'll re-add it when we deploy intelligent expert suggestions.
