### ISSUE TITLE
Error in payouts page

### ISSUE THREAD

**Issue by jeden** [airpair/airpair-com-v1-issue-tracker#359]
Got this error when accessing the payouts page:

> Payouts.getPayouts deprecated for v2 migration. Checkout consult.airpair.com this week.

**Comment by GiorgioNatili** [comment]
Same to me.

**Comment by jkresner** [comment]
Thanks - we're part way through a multi day migration. This feature will appear on the consult.airpair.com portal when we announce it thanks.

**Comment by NoellyB76** [comment]
Hey there JK, AirPair crew. I finished up an AirPair this afternoon, and the client is unable to release the funds, and I am also unable to receive funds. I'm getting the same error that others above are receiving when viewing the payouts page.

**Comment by jkresner** [comment]
Sorry still have not deployed our next release. Should be out today (next 4-5 hours) fingers crossed.

**Comment by jkresner** [comment]
I believe this is now fixed. Note we will have it on airpair.com for 1-3 days and then this page will be moved to consult.airpair.com so if you want to get paid quickly collect in the next day or so.
