### ISSUE TITLE
[2] Payout lines is invalid for releasing a payout

### ISSUE THREAD

**Issue by lmthekay** [airpair/airpair-com-v1-issue-tracker#360]
Can't Release my payment for Giorgio for session https://www.airpair.com/bookings/561d1543990a161100670bd8

I get the above error message when I click "Release my Payment"

**Comment by mwight4** [comment]
I just received the same message

**Comment by jkresner** [comment]
Hi guys, we've just deployed a huge migration (user schema has changed and early next week you will be asked to login with github instead of google.
