### ISSUE TITLE
Cant submit expert application

### ISSUE THREAD

**Issue by donnfelker** [airpair/airpair-com-v1-issue-tracker#361]
I'm trying to submit an expert application and it simply fails with "Err... sorry about this. Please tell us what happened." 

The response is an HTTP 400 with HTML as the response body. The text contains the following error message: 

  <h3>Cannot read property 'push' of undefined</h3>

**Comment by jkresner** [comment]
Thanks, will take a look today!

**Comment by kjkurtz** [comment]
I got the same error.
```
message: "Experts.create. Go to consult.airpair.com/profile deprecated in v2 migration. How did the UX get you here??"
```
I got there just by connecting a few accounts, writing up my profile, adding some technologies, and clicking 'Submit Expert Application' at the bottom.

**Comment by jkresner** [comment]
@donnfelker / @kjkurtz this feature was moved to the newer dedicated experts portal. Thanks again for reporting this.

consult.airpair.com/profile
