### ISSUE TITLE
Github Login Not Working

### ISSUE THREAD

**Issue by ditjhaba** [airpair/airpair-com-v1-issue-tracker#366]
Good day,

It's the first time I am using airpair, I am following the iOS tutorial. The thing is that I can not see your code samples as I am required to login via github which is failing and redirecting me to this URL https://www.airpair.com/auth/github/callback?code=86671177276851a8812f.

I would really love to continue using your services.

Thank you

**Comment by jkresner** [comment]
Seems to have worked for many other folks in the last 10 minutes. Perhaps your email address isn't verified or you denied the email permission?

**Comment by jkresner** [comment]
/auth/github/callback?code=912295f6e301fe587e46 <<< https://www.airpair.com/ember.js/posts/animations-in-emberjs-with-liquidfire {} Login failed. github.oauth profile has no verified email.<p><a href="https://github.com/settings/emails" target="_blank">Verify an email</a> then try again.</p>


Do you not see the error in the UI?
