### ISSUE TITLE
Markdown in proposals not rendering.

### ISSUE THREAD

**Issue by Eunoia** [airpair/airpair-com-v1-issue-tracker#40]
I frequently use markdown when writing proposals. In v1, my markdown shows up as plain text.

While markdown was designed to be fallback-able to plain text, my links don't show up and my images are no longer embedded. 

The double star to bold text looks tacky and unprofessional within v1. See screenshot:

![screen shot 2014-12-20 at 8 30 55 am](https://cloud.githubusercontent.com/assets/934880/5515515/ca2fa084-8822-11e4-984c-233e4c99618e.png)

**Comment by jkresner** [comment]
There ya go!!

Merry xMas :p

![screen shot 2015-04-29 at 4 40 05 pm](https://cloud.githubusercontent.com/assets/979542/7385736/50a4e9e0-ee8e-11e4-9bfd-8bb3e5d4966d.png)
