### ISSUE TITLE
Cannot delete a request

### ISSUE THREAD

**Issue by spookiecookie** [airpair/airpair-com-v1-issue-tracker#42]
How to delete a request? I don't see a "Delete" button anywhere.

**Comment by jkresner** [comment]
Have added the ability to delete incomplete requests. $10 has been credited on your account. Thank you!

![screen shot 2015-01-25 at 10 09 51 am](https://cloud.githubusercontent.com/assets/979542/5892601/56c37c3c-a47a-11e4-9d30-0ad4b841a8e7.png)

**Comment by spookiecookie** [comment]
Thank you. :)

2015-01-25 20:10 GMT+02:00 Jonathon Kresner <notifications@github.com>:
