### ISSUE TITLE
Cannot register as an expert

### ISSUE THREAD

**Issue by landart** [airpair/airpair-com-v1-issue-tracker#43]
From the "be an expert" registration page:
https://www.airpair.com/be-an-expert

I click on the "Sign in with Google" button and get redirected to this page:
https://www.airpair.com/v1/auth/login?return_to=%2Fbe-an-expert

![image](https://cloud.githubusercontent.com/assets/1413856/5522500/d14962fe-89b9-11e4-895d-b33c666566ab.png)

Please note that I was previously logged into the platform.

As a result, I cannot find the form to register as an expert.

Thanks for your great work!

Jorge

**Comment by dboresjo** [comment]
I have this same problem. Unable to apply to be an expert.

**Comment by massich** [comment]
Is there anyway to be an expert and client both at the same time?

**Comment by jkresner** [comment]
@massich we'll be announcing application for 2015 experts and features next week. Thanks!

**Comment by jkresner** [comment]
Expert sign up for new experts has been re-deployed. Existing experts will be able to update their profile later today or tomorrow

https://www.airpair.com/be-an-expert
