### ISSUE TITLE
Verify email fails

### ISSUE THREAD

**Issue by vikram-s-narayan** [airpair/airpair-com-v1-issue-tracker#46]
In this route: https://www.airpair.com/me?verify=$2a$08$im%2FmVA.MRzswRI24ptMaVu.fhYCdcWzNxezwMnI218RcYsS8cKugq

The verificaiton effort fails with the message:  [object Object] failed

**Comment by jkresner** [comment]
@vikram-s-narayan @brandonjmckay @benhalverson this should all be cleaned up now. Thanks for your patience.
