### ISSUE TITLE
some tags will be changed when selected in auto-complete list on Add Technolgoies page

### ISSUE THREAD

**Issue by jzinedine** [airpair/airpair-com-v1-issue-tracker#49]
Steps to reproduce:

1. Login into website
2. Click on the sidebar menu
3. Click Customize under STACK
4. Search for C# and select it
5. You will see that C will be dispalyed and saved instead of C#

That's it.

**Comment by jkresner** [comment]
https://www.airpair.com/posts/tag/c%23


![screen shot 2015-01-05 at 11 53 00 pm](https://cloud.githubusercontent.com/assets/979542/5625765/16611c06-9536-11e4-93bd-7d482ec6e8ff.png)
