### ISSUE TITLE
Can't add "C" or "Java" to my stack

### ISSUE THREAD

**Issue by abliss** [airpair/airpair-com-v1-issue-tracker#51]
your sorting algorithm puts stuff like "javafx-2" at the top, and the window doesn't let me scroll, so I can't add simply "java". Also, "C" doesn't seem to even trigger a query.

**Comment by jkresner** [comment]
Thanks I'll take a look tomorrow!

On Thursday, January 1, 2015, Adam Bliss <notifications@github.com> wrote:

> your sorting algorithm puts stuff like "javafx-2" at the top, and the
> window doesn't let me scroll, so I can't add simply "java". Also, "C"
> doesn't seem to even trigger a query.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/airpair/airpair-com-v1-issue-tracker/issues/51>.
>


-- 
Jonathon Kresner
about.me <http://about.me/jonathonkresner> | hackerpreneurialism
<http://hackerpreneurialism.com> | @hackerpreneur
<http://twitter.com/hackerpreneur>

**Comment by jkresner** [comment]
![screen shot 2015-01-05 at 6 34 02 pm](https://cloud.githubusercontent.com/assets/979542/5623461/75b9f100-9509-11e4-92c6-6579e5f913a4.png)

**Comment by jkresner** [comment]
![screen shot 2015-01-05 at 6 34 27 pm](https://cloud.githubusercontent.com/assets/979542/5623465/7f4bee9e-9509-11e4-90cf-94aeae16176b.png)

Deploying tonights thanks. Sorry this piece was done by a contractor :(
