### ISSUE TITLE
Email verification sends broken links in case email was changed.

### ISSUE THREAD

**Issue by centur** [airpair/airpair-com-v1-issue-tracker#52]
Steps to reproduce -
1. Login with google (e.g. google account is bound to YourUserName@gmail.com
2. Change your email to something completely different e,g, youremail@yourdomain.com
3. Click - send verification email.

Result:
* Tooltip says - Verification email sent to YourUserName@gmail.com (which is incorrect
* YourUserName@gmail.com will receive verification link which is valid (which is really unnecessary - email comes from google).
* youremail@yourdomain.com will receive verification link which is invalid (clicking on it will produce mentioned '[object Object] failed'

Expected result:
* Tooltip should be - Verification email sent to youremail@yourdomain.com
* Gmail account suppose to be trusted - account name is originating from google response, not user input, so you really don't need to verify it at all
* youremail@yourdomain.com link expected to be valid.

Valid link
https://www.airpair.com/me?verify=$2a$08$Zq87tPT3RG2pat53D0SuYeW1ek2XmbP56nju2iEx7So4GncL%2FgfpG

Broken link
https://www.airpair.com/me?verify=$2a$08$tJj9xQNsu/nPUKgsagsiNeeDlVwFew0OoAcwEmFCSt15V05WuJsw2

**Comment by jkresner** [comment]
Thank you kindly. Will fix this before the weekend is out!

**Comment by jkresner** [comment]
Man... this use case exposed SO many problems across our stack. The way sessions were cached and handled in the client. Our session store getting out of sync with our user store ... I've finally got through a refactoring to clean up and tie all pieces together. This flow now works with the caveat that it's sending you multiple emails to youremail@yourdomain.com, but at least with one consistent hash. Will fix the last pieces this afternoon or tomorrow. Thank you again! Do you do any paid QA work?

Jonathon

**Comment by centur** [comment]
Happy to help :) . 
About paid QA work - sorry, but not really, I'm more dev rather than QA.
