### ISSUE TITLE
Problems adding tags 'Ruby'

### ISSUE THREAD

**Issue by diasks2** [airpair/airpair-com-v1-issue-tracker#55]
I can't seem to add a tag for 'Ruby' the language.

**Comment by jkresner** [comment]
![screen shot 2015-01-05 at 6 31 34 pm](https://cloud.githubusercontent.com/assets/979542/5623437/202ba620-9509-11e4-9a60-cc7fcdcbc0cd.png)

Deploying tonight thanks.
