### ISSUE TITLE
Received "Validation failed" message

### ISSUE THREAD

**Issue by abutler3** [airpair/airpair-com-v1-issue-tracker#56]
When I attempt to setup an AirPair by clicking the Get Coding Help NEW! button in the top bar and sidebar, I get a "Validation Failed" message shown in the picture below. Even if I complete the form, it won't submit.
![screen shot 2015-01-05 at 10 15 13 am](https://cloud.githubusercontent.com/assets/297967/5615793/46ef1b06-94c4-11e4-96fd-a32f828f9798.png)

**Comment by abutler3** [comment]
Okay, as soon as I post the issue, it starts working. But something else interesting happens. When I logged in, I see my Bookmarks and Stack:
![screen shot 2015-01-05 at 10 24 18 am](https://cloud.githubusercontent.com/assets/297967/5615977/b3b8be94-94c5-11e4-8852-6e6bd56cccea.png)
But after placing the coding help, the stack and bookmarks were gone:
![screen shot 2015-01-05 at 10 26 44 am](https://cloud.githubusercontent.com/assets/297967/5615991/ce3216f8-94c5-11e4-815d-8708b28c6a6c.png)

**Comment by jkresner** [comment]
Thanks, made a few late night changes that are likely to be related. Looking into it this morning.

**Comment by jkresner** [comment]
Did you need to validate your email at all?

**Comment by jkresner** [comment]
Ok @abutler3 stack and bookmarks are back. Can you remember the steps you took for validation failed message or reproduce it?

**Comment by abutler3** [comment]
No, didn't need to validate anything. But when I went to airpair.com, I was already logged in. I did log out and then log back in. After logging back in, it seemed to fix it

**Comment by jkresner** [comment]
Closing until we can reproduce the error message. Thanks for pointing out the tags!
