### ISSUE TITLE
Code Review Tag Disapears

### ISSUE THREAD

**Issue by T-rav** [airpair/airpair-com-v1-issue-tracker#57]
When creating a new code review task with the tag of C# it disappears when I move to the experience screen. I can see it appear for about 0.5 seconds then it turns to blank as seen in this screenshot ![missing_tag](https://cloud.githubusercontent.com/assets/5384842/5625715/ef3b18ea-9588-11e4-8a75-1da37ef8545a.png)

**Comment by jkresner** [comment]
Thanks - related to a deploy from an hour ago - should be fixed now.
