### ISSUE TITLE
Tablet layout covering content

### ISSUE THREAD

**Issue by rghamilton3** [airpair/airpair-com-v1-issue-tracker#63]
Samsung Galaxy Tab 4 8.0
SAMSUNG-SM-T337A
Android 4.4.2
Google Chrome 39.0.2171.93
1280x800

Both the left and right side bars obscure content in landscape:
![screenshot_2015-01-07-16-45-44](https://cloud.githubusercontent.com/assets/2868423/5655214/0d7af04c-9691-11e4-911a-3b1c15835546.png)

**Comment by jkresner** [comment]
OK now?

https://www.airpair.com/python/posts/django-flask-pyramid

![Uploading Screen Shot 2015-03-11 at 12.08.38 PM.png . . .]()
