### ISSUE TITLE
On Dashboard Screen, stale view comes before bootstrap happens

### ISSUE THREAD

**Issue by mappmechanic** [airpair/airpair-com-v1-issue-tracker#65]
There is some static view content that is displayed on dashboard when the page first loads. After the bootstrapping, I think as the website is using AngularJS there is some scope updation happening after the load. It looks odd and can be worked upon correctly. 

The bug will generally arise on slow internet connection. I am also attaching the images for the same.

Initial Screen when Page is Loading:
![screen shot 2015-01-08 at 11 18 42 am](https://cloud.githubusercontent.com/assets/4088925/5658491/9cd9ddc4-9728-11e4-9101-8322e8dfaa2e.png)

Final Screen after the screen is completely loaded:
![screen shot 2015-01-08 at 11 18 42 am](https://cloud.githubusercontent.com/assets/4088925/5658507/dd38fc7e-9728-11e4-894d-1b06f76ad60d.png)

**Comment by mappmechanic** [comment]
I checked it, this has been resolved. You should close it. Great Work..

**Comment by jkresner** [comment]
Haven't done anything....

**Comment by mappmechanic** [comment]
I checked just now, but I am not seeing the screen which I was seeing earlier. Do not know how it got fixed :)
