### ISSUE TITLE
Typo on Billing page

### ISSUE THREAD

**Issue by joaostein** [airpair/airpair-com-v1-issue-tracker#67]
When registering the credit card information, the expiration select box has a typo on December month:

![screen shot 2015-01-09 at 4 38 32 am](https://cloud.githubusercontent.com/assets/223414/5676258/b7fb2c7a-97b9-11e4-919e-584ea14d8f16.png)

**Comment by jkresner** [comment]
Thanks @joaostein, fixed for deployment this evening. Enjoy $10 credit :).
