### ISSUE TITLE
RSS feed incorrect redirect

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#69]
Incorrectly redirecting from RSS feed to posts (https://www.airpair.com/rss)

URL: 
https://www.airpair.com/https://www.airpair.com/angularjs/posts/component-based-angularjs-directives

![screen shot 2015-01-09 at 15 30 36](https://cloud.githubusercontent.com/assets/857253/5687676/e3ec51aa-9814-11e4-8762-2804b127b059.png)

![screen shot 2015-01-09 at 15 27 32](https://cloud.githubusercontent.com/assets/857253/5687640/80c7fdf4-9814-11e4-9941-df55bd464cdd.png)

**Comment by jkresner** [comment]
Jeeeez :/

fixed now @EllDudley ?

**Comment by EllDudley** [comment]
Works! But I have another question, perhaps stupid - why does it only work in Firefox? 

This is what I get in chrome: 
![screen shot 2015-01-09 at 15 47 59](https://cloud.githubusercontent.com/assets/857253/5687877/ed71373e-9816-11e4-834f-9bbf945bb729.png)

**Comment by jkresner** [comment]
I think rss is read by many different clients / rss reads. You probably
need a chrome extension.

On Fri, Jan 9, 2015 at 1:48 PM, Ellen Dudley <notifications@github.com>
wrote:

> Works! But I have another question, perhaps stupid - why does it only work
> in Firefox?
>
> This is what I get in chrome:
> [image: screen shot 2015-01-09 at 15 47 59]
> <https://cloud.githubusercontent.com/assets/857253/5687877/ed71373e-9816-11e4-834f-9bbf945bb729.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/airpair/airpair-com-v1-issue-tracker/issues/69#issuecomment-69404811>
> .
>



-- 
Jonathon Kresner
about.me <http://about.me/jonathonkresner> | hackerpreneurialism
<http://hackerpreneurialism.com> | @hackerpreneur
<http://twitter.com/hackerpreneur>
