### ISSUE TITLE
Move Create New Post button to top of screen

### ISSUE THREAD

**Issue by EllDudley** [airpair/airpair-com-v1-issue-tracker#70]
The “create new post” is at the bottom of the screen, on my macbook well below the fold, so I don’t see it when I land on the page.

**Comment by jkresner** [comment]
![screen shot 2015-01-31 at 3 42 31 am](https://cloud.githubusercontent.com/assets/979542/5987924/373ddf4e-a8fb-11e4-9a86-1eb141bd09b2.png)

@EllDudley hope you like it :)
