### ISSUE TITLE
can't set username

### ISSUE THREAD

**Issue by cespivo** [airpair/airpair-com-v1-issue-tracker#75]
It says: Cast to string failed for value "undefined" at path "name"

**Comment by jkresner** [comment]
Thanks have got a screen shit. I've been noticing this one in the logs.

On Saturday, January 10, 2015, Jan Češpivo <notifications@github.com> wrote:

> It says: Cast to string failed for value "undefined" at path "name"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/airpair/airpair-com-v1-issue-tracker/issues/75>.
>


-- 
Jonathon Kresner
about.me <http://about.me/jonathonkresner> | hackerpreneurialism
<http://hackerpreneurialism.com> | @hackerpreneur
<http://twitter.com/hackerpreneur>

**Comment by jkresner** [comment]
@cespivo this should be fixed. A completely different code path is now in place. I've credited your account $10. Thank you!
