### ISSUE TITLE
Notification of inactive request

### ISSUE THREAD

**Issue by snuggs** [airpair/airpair-com-v1-issue-tracker#77]
Use case: https://www.airpair.com/review/546ace56e41bdc02001344e2?utm_medium=farm-link&utm_campaign=farm-nov&utm_term=Ruby%20on%20Rails&utm_source=twitter-airpair

Proposed feature to display notification prior to allowing pair to send a reply:
e.g. ![Existing Notification](https://pbs.twimg.com/media/B7JLD4iCQAEFRau.png:large)

**Comment by jkresner** [comment]
Hey @snuggs, I want to apologize for how long this has taken. I got very side tracked these last weeks with all the authoring stuff we've been working on and we haven't had enough dev resource to push both core expert stuff and the comp. The good news is that the comp stuff is mostly done and for the next 4-6 weeks I will be primarily focused on expert features, and part of the reason I didn't get to this part of the code is we're about to step up the experience around replying to requests by 10x. 

Finally I'm planning to build a lot of it open source. You would be most welcome to code review and fix bugs in your reach as I go:

https://github.com/airpair/experts.airpair.com

![screen shot 2015-03-12 at 1 19 06 pm](https://cloud.githubusercontent.com/assets/979542/6627372/e4545daa-c8ba-11e4-9925-9885ace6b640.png)
