### ISSUE TITLE
Send verification failed

### ISSUE THREAD

**Issue by rabolf** [airpair/airpair-com-v1-issue-tracker#78]
I verified my Email but it still shows as not verified under Account tab. after I clicked Send Verification Email button it shows "[object Object] failed" error

![airpair](https://cloud.githubusercontent.com/assets/10519585/5725987/fe46e9f6-9b6c-11e4-8a72-95a2b9dab444.jpg)

**Comment by jkresner** [comment]
Thanks fixing all this today. Cheers.

**Comment by jkresner** [comment]
@rabolf should be fixed. If you'd like to test if on a different email address, I would be happy to credit your account a second $10 amount. We can delete the account manually after that on our end if you let me know the email address you used.

**Comment by rabolf** [comment]
first bug is fixed. thanks. now I see another bug but it's not really important.

If I click "send verification email" button and leave the page open then go to my inbox and verify my email then get back to account page (the old one that still is open) and click send verification again it shows an error, it's better to show a proper message.

![airpair 1](https://cloud.githubusercontent.com/assets/10519585/5779916/fac9a9f2-9dbb-11e4-8857-2c6282d65a47.jpg)

**Comment by jkresner** [comment]
Thanks, I'm not sure if you caused that or something else crashed the site and you just go lucky. Will investigate.

**Comment by jkresner** [comment]
This certainly was a bug that was crashing the site for everyone else :P... Fix and friendly error message being deployed in 20 mins. Thank you!!!

![screen shot 2015-01-16 at 7 30 12 pm](https://cloud.githubusercontent.com/assets/979542/5787487/2138eed2-9db6-11e4-86c5-bcbefd3f482f.png)
