### ISSUE TITLE
credit card: old card shows as 'undefined', cannot delete

### ISSUE THREAD

**Issue by mhurwi** [airpair/airpair-com-v1-issue-tracker#80]
Some time ago, I setup an AirPair account.  Today, I came back to book an hour.  

My old credit card is still on file, but it is displayed as 'undefined'.  I tried to delete.  A blank flash message appeared, the card was not deleted.

I went through and booked the hour anyway, thinking the card was actually undefined and that I would be prompted to add a card.  But, my old card was charged. And I cannot delete my old card.

![airpair___ember_js_and_ember-cli_request](https://cloud.githubusercontent.com/assets/471126/5779585/99f4067e-9d69-11e4-91c5-38440651ae22.png)

**Comment by jkresner** [comment]
Thank you. Will address / fix in the next 48 hours.

**Comment by jkresner** [comment]
Fixed in deploy last night cheers! Have added $10 to your account.
