### ISSUE TITLE
pyparsing topic shows up as "undefined"

### ISSUE THREAD

**Issue by ptmcg** [airpair/airpair-com-v1-issue-tracker#85]
![airpair_screenshot](https://cloud.githubusercontent.com/assets/383875/5797096/b6b66b46-9f79-11e4-912a-e95a2bc91f27.jpg)

**Comment by jkresner** [comment]
Fixed thank you. $10 had been added to your account :)

![screen shot 2015-01-26 at 10 21 44 pm](https://cloud.githubusercontent.com/assets/979542/5914392/c3ebb614-a5a9-11e4-9df6-743d7fd2d7a0.png)
