### ISSUE TITLE
Can't tell a request is closed

### ISSUE THREAD

**Issue by brandonjmckay** [airpair/airpair-com-v1-issue-tracker#86]
I went to https://www.airpair.com/review/54b92dd1b8260409003629dd to repond to a request, but after filling out the form and submitting it says I can't because it isn't active.

When I reload the page I can fill out the form again, but I get the same message on submitting.

**Comment by jkresner** [comment]
Thanks @brandonjmckay , will cover this in review ux overhaul next week to make replying way easier. Cheers!

Error: Cannot reply to this request, as it is not active
PUT /v1/api/requests/54b92dd1b8260409003629dd/reply/549f9d443a0ad90200e7a72e
Brandon J McKay themckaystudios@gmail.com 549f9a788f8c80299bcc58a9
 << https://www.airpair.com/review/54b92dd1b8260409003629dd
isBot:false:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36

 {"expertStatus":"available","expertComment":"I can help you with that.","expertAvailability":"I'm on PST. I can do a session most afternoons except Thursday, and Sunday. I can do 7- 8:30am weekdays (exc. Thursday). Wednesday night might be open. Saturday-days are fine."}

 Error: Cannot reply to this request, as it is not active
    at /app/_api.js:60:19
    at Layer.handle [as handle_

**Comment by Eunoia** [comment]
+1 noticed this as well.

**Comment by Eunoia** [comment]
Also happens when turning down a request.

**Comment by jkresner** [comment]
Thanks guys, lots of improvements on replying process page coming next week. This bug will be cleaned up in the process. Thanks for you patience.

**Comment by jkresner** [comment]
Hey @brandonjmckay & @Eunoia , I want to apologize for how long this has taken. I got very side tracked these last weeks with all the authoring stuff we've been working on and we haven't had enough dev resource to push both core expert stuff and the comp. The good news is that the comp stuff is mostly done and for the next 4-6 weeks I will be primarily focused on expert features. More good news is I'm planning to build a lot of it open source. You would be most welcome to code review and fix bugs in your reach as I go:

https://github.com/airpair/experts.airpair.com

![screen shot 2015-03-12 at 1 19 06 pm](https://cloud.githubusercontent.com/assets/979542/6627372/e4545daa-c8ba-11e4-9925-9885ace6b640.png)

**Comment by brandonjmckay** [comment]
Coool beans. Haven't had much free time to pair recently anyways.
