### ISSUE TITLE
Booking link not working

### ISSUE THREAD

**Issue by jeffwhelpley** [airpair/airpair-com-v1-issue-tracker#88]
When I click on my booking link in the calendar invite that was sent out to me, I get a web page with the following error:

Cannot GET /booking/54b867564c39490900187af5

This is for the URL: https://www.airpair.com/booking/54b867564c39490900187af5

**Comment by jkresner** [comment]
Thanks, this page will be appearing next week :)

On Mon, Jan 19, 2015 at 1:45 PM, jeffwhelpley <notifications@github.com>
wrote:

> When I click on my booking link in the calendar invite that was sent out
> to me, I get a web page with the following error:
>
> Cannot GET /booking/54b867564c39490900187af5
>
> This is for the URL:
> https://www.airpair.com/booking/54b867564c39490900187af5
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/airpair/airpair-com-v1-issue-tracker/issues/88>.
>



-- 
Jonathon Kresner
about.me <http://about.me/jonathonkresner> | hackerpreneurialism
<http://hackerpreneurialism.com> | @hackerpreneur
<http://twitter.com/hackerpreneur>

**Comment by jkresner** [comment]
Page is a little half done, but here you go

![screen shot 2015-05-14 at 9 54 26 am](https://cloud.githubusercontent.com/assets/979542/7636923/235f6a4a-fa1f-11e4-9ce2-766c004f8cc4.png)
