### ISSUE TITLE
Same technology tag can be added multiple times

### ISSUE THREAD

**Issue by vikram-s-narayan** [airpair/airpair-com-v1-issue-tracker#90]
![screen shot 2015-01-21 at 8 44 34 pm](https://cloud.githubusercontent.com/assets/5373305/5838570/57272e36-a1ae-11e4-9034-5f2a2c59d065.png)
On https://www.airpair.com/help/request you can type and add the same technology tag multiple times.

**Comment by jkresner** [comment]
Fix deployed thank you!
