### ISSUE TITLE
You can no longer add a tag that is not in the database

### ISSUE THREAD

**Issue by aareese** [airpair/airpair-com-v1-issue-tracker#92]
You should be able to add it. At the very least, the support text should say 'tag not found, please choose a different tag or check the spelling' if you type something that's not in the database.

![airpair](https://cloud.githubusercontent.com/assets/493691/5846859/41304586-a17c-11e4-9e61-b253632faca1.png)

**Comment by jkresner** [comment]
Added :)

![screen shot 2015-04-22 at 11 07 28 am](https://cloud.githubusercontent.com/assets/979542/7265633/3785488c-e8e0-11e4-98c4-e4af9b3cadb5.png)
![screen shot 2015-04-22 at 11 07 36 am](https://cloud.githubusercontent.com/assets/979542/7265634/3b07c8fe-e8e0-11e4-8d8a-8c0e05174fad.png)
![screen shot 2015-04-22 at 11 07 28 am](https://cloud.githubusercontent.com/assets/979542/7265635/3e22b242-e8e0-11e4-9289-7a4ea9d28b0e.png)
