### ISSUE TITLE
Layout Bug on your Bug...callout

### ISSUE THREAD

**Issue by nrutter2000** [airpair/airpair-com-v1-issue-tracker#95]
**Problem**:
If you go here: https://www.airpair.com/v1
View at a mobile/minimal width - You'll see that part of the layout is non-responsive, especially the 'See a bug' section, it overflows to the right!

**Solution**:
It's down to this bad boy having a fixed width and height (because of the connect-4 background image) in...

*index.css*
```
section.comingsoon {
background: url(../img/pages/coming/background.jpg);
/* width: 900px; */
/* height: 600px; */
}
```

Take them out for mobile (max-width: 640px breakpoint) and you're done.

Cheers!

**Comment by jkresner** [comment]
Fix deployed thank you! I can't find your account in our database to credit you $10 :)

**Comment by nrutter2000** [comment]
I'll be sure to make one and let you know Tuesday! Cheers ;)
