### ISSUE TITLE
Unable to Join

### ISSUE THREAD

**Issue by mhulsey2** [airpair/airpair-com-v1-issue-tracker#98]
I wasn't able to "Join AirPair" from the About page. After I filled in my email, name, and password, and then clicked Create Account, nothing would happen. I tried several times. 

However, I was able to join from the Live Coding Help page.

**Comment by jkresner** [comment]
Fix deployed thank you. If you let me know your name, I'd like to credit your account $10 :).

**Comment by mhulsey2** [comment]
Great. My name is Michel Hulsey.  

     On Saturday, January 24, 2015 12:23 PM, Jonathon Kresner <notifications@github.com> wrote:
   

 Fix deployed thank you. If you let me know your name, I'd like to credit your account $10 :).—
