### ISSUE TITLE
After joining, unable to log in after logging out. 

### ISSUE THREAD

**Issue by mhulsey2** [airpair/airpair-com-v1-issue-tracker#99]
I joined then logged out. Now I can't log back in.

**Comment by jkresner** [comment]
Did you get an email to set your password. If you missed that, you can try the forgotten password flow from the login page?

**Comment by mhulsey2** [comment]
I reset my password and was able to log in through that route. But I logged out then tried to log in again and cannot. I enter my email and password, press the log in button and nothing. The button does turn orange, but nothing else. 

 

     On Saturday, January 24, 2015 12:23 PM, Jonathon Kresner <notifications@github.com> wrote:
   

 Closed #99.—

**Comment by jkresner** [comment]
That flow just worked for me...
